<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var app\models\MrbsEntry $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="mrbs-entry-form">

    <?php $form = ActiveForm::begin([
    'id' => 'MrbsEntry',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-danger',
    'fieldConfig' => [
             'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
             'horizontalCssClasses' => [
                 'label' => 'col-sm-2',
                 #'offset' => 'col-sm-offset-4',
                 'wrapper' => 'col-sm-8',
                 'error' => '',
                 'hint' => '',
             ],
         ],
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            

<!-- attribute start_time -->
			<?= $form->field($model, 'start_time')->textInput() ?>

<!-- attribute end_time -->
			<?= $form->field($model, 'end_time')->textInput() ?>

<!-- attribute entry_type -->
			<?= $form->field($model, 'entry_type')->textInput() ?>

<!-- attribute repeat_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'repeat_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\MrbsRepeat::find()->all(), 'id', 'name'),
    [
        'prompt' => 'Select',
        'disabled' => (isset($relAttributes) && isset($relAttributes['repeat_id'])),
    ]
); ?>

<!-- attribute room_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'room_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\models\MrbsRoom::find()->all(), 'id', 'id'),
    [
        'prompt' => 'Select',
        'disabled' => (isset($relAttributes) && isset($relAttributes['room_id'])),
    ]
); ?>

<!-- attribute status -->
			<?= $form->field($model, 'status')->textInput() ?>

<!-- attribute reminded -->
			<?= $form->field($model, 'reminded')->textInput() ?>

<!-- attribute info_time -->
			<?= $form->field($model, 'info_time')->textInput() ?>

<!-- attribute ical_sequence -->
			<?= $form->field($model, 'ical_sequence')->textInput() ?>

<!-- attribute timestamp -->
			<?= $form->field($model, 'timestamp')->textInput() ?>

<!-- attribute description -->
			<?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

<!-- attribute info_text -->
			<?= $form->field($model, 'info_text')->textarea(['rows' => 6]) ?>

<!-- attribute create_by -->
			<?= $form->field($model, 'create_by')->textInput(['maxlength' => true]) ?>

<!-- attribute modified_by -->
			<?= $form->field($model, 'modified_by')->textInput(['maxlength' => true]) ?>

<!-- attribute info_user -->
			<?= $form->field($model, 'info_user')->textInput(['maxlength' => true]) ?>

<!-- attribute name -->
			<?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

<!-- attribute type -->
			<?= $form->field($model, 'type')->textInput(['maxlength' => true]) ?>

<!-- attribute meeting_status -->
			<?= $form->field($model, 'meeting_status')->textInput(['maxlength' => true]) ?>

<!-- attribute ical_uid -->
			<?= $form->field($model, 'ical_uid')->textInput(['maxlength' => true]) ?>

<!-- attribute ical_recur_id -->
			<?= $form->field($model, 'ical_recur_id')->textInput(['maxlength' => true]) ?>
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                    'encodeLabels' => false,
                    'items' => [ 
                        [
    'label'   => Yii::t('models', 'MrbsEntry'),
    'content' => $this->blocks['main'],
    'active'  => true,
],
                    ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? 'Create' : 'Save'),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

