<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\controllers\base;

use app\models\FotocopyLogTbl;
    use app\models\search\XeroxLogSearch;
use yii\web\Controller;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\filters\AccessControl;
use dmstr\bootstrap\Tabs;

/**
* XeroxLogController implements the CRUD actions for FotocopyLogTbl model.
*/
class XeroxLogController extends Controller
{


/**
* @var boolean whether to enable CSRF validation for the actions in this controller.
* CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
*/
public $enableCsrfValidation = false;


/**
* Lists all FotocopyLogTbl models.
* @return mixed
*/
public function actionIndex()
{
    $searchModel  = new XeroxLogSearch;
    $dataProvider = $searchModel->search($_GET);

Tabs::clearLocalStorage();

Url::remember();
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->render('index', [
'dataProvider' => $dataProvider,
    'searchModel' => $searchModel,
]);
}

/**
* Displays a single FotocopyLogTbl model.
* @param string $job_number_id1
*
* @return mixed
*/
public function actionView($job_number_id1)
{
\Yii::$app->session['__crudReturnUrl'] = Url::previous();
Url::remember();
Tabs::rememberActiveState();

return $this->render('view', [
'model' => $this->findModel($job_number_id1),
]);
}

/**
* Creates a new FotocopyLogTbl model.
* If creation is successful, the browser will be redirected to the 'view' page.
* @return mixed
*/
public function actionCreate()
{
$model = new FotocopyLogTbl;

try {
if ($model->load($_POST) && $model->save()) {
return $this->redirect(['view', 'job_number_id1' => $model->job_number_id1]);
} elseif (!\Yii::$app->request->isPost) {
$model->load($_GET);
}
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
$model->addError('_exception', $msg);
}
return $this->render('create', ['model' => $model]);
}

/**
* Updates an existing FotocopyLogTbl model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param string $job_number_id1
* @return mixed
*/
public function actionUpdate($job_number_id1)
{
$model = $this->findModel($job_number_id1);

if ($model->load($_POST) && $model->save()) {
return $this->redirect(Url::previous());
} else {
return $this->render('update', [
'model' => $model,
]);
}
}

/**
* Deletes an existing FotocopyLogTbl model.
* If deletion is successful, the browser will be redirected to the 'index' page.
* @param string $job_number_id1
* @return mixed
*/
public function actionDelete($job_number_id1)
{
try {
$this->findModel($job_number_id1)->delete();
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
\Yii::$app->getSession()->addFlash('error', $msg);
return $this->redirect(Url::previous());
}

// TODO: improve detection
$isPivot = strstr('$job_number_id1',',');
if ($isPivot == true) {
return $this->redirect(Url::previous());
} elseif (isset(\Yii::$app->session['__crudReturnUrl']) && \Yii::$app->session['__crudReturnUrl'] != '/') {
Url::remember(null);
$url = \Yii::$app->session['__crudReturnUrl'];
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->redirect($url);
} else {
return $this->redirect(['index']);
}
}

/**
* Finds the FotocopyLogTbl model based on its primary key value.
* If the model is not found, a 404 HTTP exception will be thrown.
* @param string $job_number_id1
* @return FotocopyLogTbl the loaded model
* @throws HttpException if the model cannot be found
*/
protected function findModel($job_number_id1)
{
if (($model = FotocopyLogTbl::findOne($job_number_id1)) !== null) {
return $model;
} else {
throw new HttpException(404, 'The requested page does not exist.');
}
}
}
