<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.ACCOUNT_BUDGET_RATE".
 *
 * @property integer $URUT
 * @property string $CURR
 * @property double $RATE
 * @property string $START_DATE
 * @property string $END_DATE
 * @property string $USER_ID
 * @property string $USER_DESC
 * @property string $LAST_UPDATE
 * @property string $aliasModel
 */
abstract class AccountBudgetRate extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.ACCOUNT_BUDGET_RATE';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_wsus');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['CURR', 'USER_ID', 'USER_DESC'], 'string'],
            [['RATE'], 'number'],
            [['START_DATE', 'END_DATE', 'LAST_UPDATE'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'URUT' => 'Urut',
            'CURR' => 'Curr',
            'RATE' => 'Rate',
            'START_DATE' => 'Start  Date',
            'END_DATE' => 'End  Date',
            'USER_ID' => 'User  ID',
            'USER_DESC' => 'User  Desc',
            'LAST_UPDATE' => 'Last  Update',
        ];
    }




}
