<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.ASSET_STOCK_TAKE_SUMMARY".
 *
 * @property integer $schedule_id
 * @property string $CC_GROUP
 * @property integer $total_ok
 * @property integer $total_ng
 * @property integer $total_repair
 * @property integer $total_standby
 * @property integer $ng_plan_scrap
 * @property integer $label_y
 * @property integer $label_n
 * @property integer $total_open
 * @property integer $total_close
 * @property integer $total
 * @property string $aliasModel
 */
abstract class AssetStockTakeSummary extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.ASSET_STOCK_TAKE_SUMMARY';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['schedule_id', 'total_ok', 'total_ng', 'total_repair', 'total_standby', 'ng_plan_scrap', 'label_y', 'label_n', 'total_open', 'total_close', 'total'], 'integer'],
            [['CC_GROUP'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'schedule_id' => 'Schedule ID',
            'CC_GROUP' => 'Cc Group',
            'total_ok' => 'Total Ok',
            'total_ng' => 'Total Ng',
            'total_repair' => 'Total Repair',
            'total_standby' => 'Total Standby',
            'ng_plan_scrap' => 'Ng Plan Scrap',
            'label_y' => 'Label Y',
            'label_n' => 'Label N',
            'total_open' => 'Total Open',
            'total_close' => 'Total Close',
            'total' => 'Total',
        ];
    }




}
