<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.ASSET_LOC_TBL".
 *
 * @property string $LOC
 * @property string $LOC_DESC
 * @property string $LOC_GROUP
 * @property string $LOC_GROUP_DESC
 * @property string $LOC_AREA
 * @property string $LOC_TYPE
 * @property string $NIK_SUN_FISH
 * @property string $NAMA_KARYAWAN
 * @property string $aliasModel
 */
abstract class AssetLocTbl extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.ASSET_LOC_TBL';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['LOC'], 'required'],
            [['LOC', 'LOC_DESC', 'LOC_GROUP', 'LOC_GROUP_DESC', 'LOC_AREA', 'LOC_TYPE', 'NIK_SUN_FISH', 'NAMA_KARYAWAN'], 'string'],
            [['LOC'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'LOC' => 'Loc',
            'LOC_DESC' => 'Loc  Desc',
            'LOC_GROUP' => 'Loc  Group',
            'LOC_GROUP_DESC' => 'Loc  Group  Desc',
            'LOC_AREA' => 'Loc  Area',
            'LOC_TYPE' => 'Loc  Type',
            'NIK_SUN_FISH' => 'Nik  Sun  Fish',
            'NAMA_KARYAWAN' => 'Nama  Karyawan',
        ];
    }




}
