<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.AUDIT_PATROL_TBL".
 *
 * @property integer $ID
 * @property string $PATROL_PERIOD
 * @property string $PATROL_DATE
 * @property string $PATROL_DATETIME
 * @property string $CC_ID
 * @property string $CC_GROUP
 * @property string $CC_DESC
 * @property string $LOC_ID
 * @property string $LOC_DESC
 * @property string $LOC_DETAIL
 * @property integer $CATEGORY
 * @property string $TOPIC
 * @property string $DESCRIPTION
 * @property string $ACTION
 * @property string $AUDITOR
 * @property string $AUDITEE
 * @property string $PIC_ID
 * @property string $PIC_NAME
 * @property string $USER_ID
 * @property string $USER_NAME
 * @property string $DELETE_BY_ID
 * @property string $DELETE_BY_NAME
 * @property string $DELETE_DATETIME
 * @property string $DELETE_REMARK
 * @property string $IMAGE_BEFORE_1
 * @property string $IMAGE_BEFORE_2
 * @property string $IMAGE_BEFORE_3
 * @property string $IMAGE_AFTER_1
 * @property string $IMAGE_AFTER_2
 * @property string $IMAGE_AFTER_3
 * @property string $STATUS
 * @property integer $FLAG
 * @property string $aliasModel
 */
abstract class AuditPatrolTbl extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.AUDIT_PATROL_TBL';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['PATROL_DATE', 'PATROL_DATETIME', 'DELETE_DATETIME'], 'safe'],
            [['CATEGORY', 'FLAG'], 'integer'],
            [['DESCRIPTION', 'ACTION', 'DELETE_REMARK', 'IMAGE_BEFORE_1', 'IMAGE_BEFORE_2', 'IMAGE_BEFORE_3', 'IMAGE_AFTER_1', 'IMAGE_AFTER_2', 'IMAGE_AFTER_3'], 'string'],
            [['PATROL_PERIOD', 'CC_ID', 'CC_GROUP', 'CC_DESC', 'LOC_ID', 'LOC_DESC', 'PIC_ID', 'USER_ID', 'DELETE_BY_ID'], 'string', 'max' => 50],
            [['LOC_DETAIL', 'TOPIC', 'AUDITOR', 'AUDITEE', 'PIC_NAME', 'USER_NAME', 'DELETE_BY_NAME'], 'string', 'max' => 150],
            [['STATUS'], 'string', 'max' => 1]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ID' => 'ID',
            'PATROL_PERIOD' => 'Patrol Period',
            'PATROL_DATE' => 'Patrol Date',
            'PATROL_DATETIME' => 'Patrol Datetime',
            'CC_ID' => 'Cc ID',
            'CC_GROUP' => 'Cc Group',
            'CC_DESC' => 'Cc Desc',
            'LOC_ID' => 'Loc ID',
            'LOC_DESC' => 'Loc Desc',
            'LOC_DETAIL' => 'Loc Detail',
            'CATEGORY' => 'Category',
            'TOPIC' => 'Topic',
            'DESCRIPTION' => 'Description',
            'ACTION' => 'Action',
            'AUDITOR' => 'Auditor',
            'AUDITEE' => 'Auditee',
            'PIC_ID' => 'Pic ID',
            'PIC_NAME' => 'Pic Name',
            'USER_ID' => 'User ID',
            'USER_NAME' => 'User Name',
            'DELETE_BY_ID' => 'Delete By ID',
            'DELETE_BY_NAME' => 'Delete By Name',
            'DELETE_DATETIME' => 'Delete Datetime',
            'DELETE_REMARK' => 'Delete Remark',
            'IMAGE_BEFORE_1' => 'Image Before 1',
            'IMAGE_BEFORE_2' => 'Image Before 2',
            'IMAGE_BEFORE_3' => 'Image Before 3',
            'IMAGE_AFTER_1' => 'Image After 1',
            'IMAGE_AFTER_2' => 'Image After 2',
            'IMAGE_AFTER_3' => 'Image After 3',
            'STATUS' => 'Status',
            'FLAG' => 'Flag',
        ];
    }




}
