<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.BOOKING_SHIP_TRACK_02".
 *
 * @property string $BOOKING_ID
 * @property string $USER_ID
 * @property string $USER_DESC
 * @property string $PUR_LOC
 * @property string $PICKUP_PLAN
 * @property string $PICKUP_ACTUAL
 * @property integer $STAT_ID
 * @property string $STAT_ID_DESC
 * @property string $SHIPPER
 * @property double $QTY
 * @property double $NET_WEIGHT
 * @property double $GROSS_WEIGHT
 * @property double $MEASUREMENT
 * @property string $NOTE
 * @property string $PIC_ID
 * @property string $PIC_DESC
 * @property string $CREATED_DATE
 * @property string $BOOKING_ID_DTR
 * @property string $ITEM
 * @property string $ITEM_DESC
 * @property string $UM
 * @property double $ORDER_QTY
 * @property double $RCV_QTY
 * @property double $BO_QTY
 * @property string $STAT
 * @property string $PO_NO
 * @property string $DISCREPANCY
 * @property string $YEMI_ARRIVAL
 * @property string $YEAR
 * @property string $PERIOD
 * @property integer $WEEK
 * @property string $DATE
 * @property string $TRANS_MTHD
 * @property string $aliasModel
 */
abstract class BookingShipTrack02 extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.BOOKING_SHIP_TRACK_02';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_wsus');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['BOOKING_ID', 'USER_ID', 'USER_DESC', 'PUR_LOC', 'PICKUP_PLAN', 'STAT_ID', 'STAT_ID_DESC', 'SHIPPER', 'PIC_ID', 'PIC_DESC', 'CREATED_DATE'], 'required'],
            [['BOOKING_ID', 'USER_ID', 'USER_DESC', 'PUR_LOC', 'STAT_ID_DESC', 'SHIPPER', 'NOTE', 'PIC_ID', 'PIC_DESC', 'BOOKING_ID_DTR', 'ITEM', 'ITEM_DESC', 'UM', 'STAT', 'PO_NO', 'DISCREPANCY', 'YEAR', 'PERIOD', 'DATE', 'TRANS_MTHD'], 'string'],
            [['PICKUP_PLAN', 'PICKUP_ACTUAL', 'CREATED_DATE', 'YEMI_ARRIVAL'], 'safe'],
            [['STAT_ID', 'WEEK'], 'integer'],
            [['QTY', 'NET_WEIGHT', 'GROSS_WEIGHT', 'MEASUREMENT', 'ORDER_QTY', 'RCV_QTY', 'BO_QTY'], 'number']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'BOOKING_ID' => 'Booking  ID',
            'USER_ID' => 'User  ID',
            'USER_DESC' => 'User  Desc',
            'PUR_LOC' => 'Pur  Loc',
            'PICKUP_PLAN' => 'Pickup  Plan',
            'PICKUP_ACTUAL' => 'Pickup  Actual',
            'STAT_ID' => 'Stat  ID',
            'STAT_ID_DESC' => 'Stat  Id  Desc',
            'SHIPPER' => 'Shipper',
            'QTY' => 'Qty',
            'NET_WEIGHT' => 'Net  Weight',
            'GROSS_WEIGHT' => 'Gross  Weight',
            'MEASUREMENT' => 'Measurement',
            'NOTE' => 'Note',
            'PIC_ID' => 'Pic  ID',
            'PIC_DESC' => 'Pic  Desc',
            'CREATED_DATE' => 'Created  Date',
            'BOOKING_ID_DTR' => 'Booking  Id  Dtr',
            'ITEM' => 'Item',
            'ITEM_DESC' => 'Item  Desc',
            'UM' => 'Um',
            'ORDER_QTY' => 'Order  Qty',
            'RCV_QTY' => 'Rcv  Qty',
            'BO_QTY' => 'Bo  Qty',
            'STAT' => 'Stat',
            'PO_NO' => 'Po  No',
            'DISCREPANCY' => 'Discrepancy',
            'YEMI_ARRIVAL' => 'Yemi  Arrival',
            'YEAR' => 'Year',
            'PERIOD' => 'Period',
            'WEEK' => 'Week',
            'DATE' => 'Date',
            'TRANS_MTHD' => 'Trans  Mthd',
        ];
    }




}
