<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.CUTI_TBL".
 *
 * @property string $CUTI_ID
 * @property string $NIK
 * @property string $NAMA_KARYAWAN
 * @property string $CATEGORY
 * @property integer $TAHUN
 * @property integer $JUMLAH_CUTI
 * @property string $aliasModel
 */
abstract class CutiTbl extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.CUTI_TBL';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['CUTI_ID'], 'required'],
            [['CUTI_ID', 'NIK', 'NAMA_KARYAWAN', 'CATEGORY'], 'string'],
            [['TAHUN', 'JUMLAH_CUTI'], 'integer'],
            [['CUTI_ID'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'CUTI_ID' => 'Cuti  ID',
            'NIK' => 'Nik',
            'NAMA_KARYAWAN' => 'Nama  Karyawan',
            'CATEGORY' => 'Category',
            'TAHUN' => 'Tahun',
            'JUMLAH_CUTI' => 'Jumlah  Cuti',
        ];
    }




}
