<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "daily_production_output".
 *
 * @property string $id
 * @property string $period
 * @property string $proddate
 * @property string $gmc
 * @property integer $act_qty
 * @property string $aliasModel
 */
abstract class DailyProductionOutput extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'daily_production_output';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_mis7');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id'], 'required'],
            [['proddate'], 'safe'],
            [['act_qty'], 'integer'],
            [['id', 'gmc'], 'string', 'max' => 30],
            [['period'], 'string', 'max' => 10],
            [['id'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'period' => 'Period',
            'proddate' => 'Proddate',
            'gmc' => 'Gmc',
            'act_qty' => 'Act Qty',
        ];
    }




}
