<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "dpr_line_efficiency_view_02".
 *
 * @property integer $period
 * @property string $proddate
 * @property string $line
 * @property double $qty_time
 * @property double $mp_time
 * @property double $efficiency
 * @property string $aliasModel
 */
abstract class DprLineEfficiencyView02 extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'dpr_line_efficiency_view_02';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_mis7');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['period'], 'integer'],
            [['proddate', 'line'], 'required'],
            [['qty_time', 'mp_time', 'efficiency'], 'number'],
            [['proddate'], 'string', 'max' => 10],
            [['line'], 'string', 'max' => 15]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'period' => 'Period',
            'proddate' => 'Proddate',
            'line' => 'Line',
            'qty_time' => 'Qty Time',
            'mp_time' => 'Mp Time',
            'efficiency' => 'Efficiency',
        ];
    }




}
