<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "dpr_line_eff02".
 *
 * @property integer $period
 * @property string $line
 * @property double $eff
 * @property string $aliasModel
 */
abstract class DprLineEff02 extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'dpr_line_eff02';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_mis7');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['period'], 'integer'],
            [['line'], 'required'],
            [['eff'], 'number'],
            [['line'], 'string', 'max' => 15]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'period' => 'Period',
            'line' => 'Line',
            'eff' => 'Eff',
        ];
    }




}
