<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "out_dross".
 *
 * @property integer $id
 * @property integer $dross
 * @property integer $dross_recycle
 * @property string $mesin
 * @property string $tgl
 * @property string $aliasModel
 */
abstract class DrossOutput extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'out_dross';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_mis7');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['dross', 'dross_recycle', 'mesin', 'tgl'], 'required'],
            [['dross', 'dross_recycle'], 'integer'],
            [['mesin'], 'string', 'max' => 15],
            [['tgl'], 'string', 'max' => 11]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'dross' => 'Dross',
            'dross_recycle' => 'Dross Recycle',
            'mesin' => 'Mesin',
            'tgl' => 'Tgl',
        ];
    }




}
