<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "input_tm".
 *
 * @property integer $id
 * @property string $mesin
 * @property integer $new
 * @property integer $recycle
 * @property string $tgl_in
 * @property string $aliasModel
 */
abstract class DrossInput extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'input_tm';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_mis7');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['mesin', 'new', 'recycle', 'tgl_in'], 'required'],
            [['new', 'recycle'], 'integer'],
            [['mesin'], 'string', 'max' => 15],
            [['tgl_in'], 'string', 'max' => 200]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'mesin' => 'Mesin',
            'new' => 'New',
            'recycle' => 'Recycle',
            'tgl_in' => 'Tgl In',
        ];
    }




}
