<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.EMP_INTERVIEW_YUBISASHI".
 *
 * @property string $ID
 * @property string $EMP_ID
 * @property string $EMP_NAME
 * @property integer $FISCAL_YEAR
 * @property string $DEPARTMENT
 * @property string $COST_CENTER_CODE
 * @property string $COST_CENTER_NAME
 * @property integer $YAMAHA_DIAMOND
 * @property integer $K3
 * @property integer $SLOGAN_KUALITAS
 * @property integer $KESELAMATAN_LALU_LINTAS
 * @property integer $KOMITMENT_BERKENDARA
 * @property integer $BUDAYA_KERJA
 * @property string $LAST_UPDATE
 * @property string $aliasModel
 */
abstract class EmpInterviewYubisashi extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.EMP_INTERVIEW_YUBISASHI';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ID'], 'required'],
            [['EMP_NAME'], 'string'],
            [['FISCAL_YEAR', 'YAMAHA_DIAMOND', 'K3', 'SLOGAN_KUALITAS', 'KESELAMATAN_LALU_LINTAS', 'KOMITMENT_BERKENDARA', 'BUDAYA_KERJA'], 'integer'],
            [['LAST_UPDATE'], 'safe'],
            [['ID', 'EMP_ID', 'DEPARTMENT', 'COST_CENTER_CODE'], 'string', 'max' => 50],
            [['COST_CENTER_NAME'], 'string', 'max' => 150],
            [['ID'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ID' => 'ID',
            'EMP_ID' => 'Emp ID',
            'EMP_NAME' => 'Emp Name',
            'FISCAL_YEAR' => 'Fiscal Year',
            'DEPARTMENT' => 'Department',
            'COST_CENTER_CODE' => 'Cost Center Code',
            'COST_CENTER_NAME' => 'Cost Center Name',
            'YAMAHA_DIAMOND' => 'Yamaha Diamond',
            'K3' => 'K3',
            'SLOGAN_KUALITAS' => 'Slogan Kualitas',
            'KESELAMATAN_LALU_LINTAS' => 'Keselamatan Lalu Lintas',
            'KOMITMENT_BERKENDARA' => 'Komitment Berkendara',
            'BUDAYA_KERJA' => 'Budaya Kerja',
            'LAST_UPDATE' => 'Last Update',
        ];
    }




}
