<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.FISCAL_TBL".
 *
 * @property string $PERIOD
 * @property string $YEAR
 * @property string $FISCAL
 * @property string $aliasModel
 */
abstract class FiscalTbl extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.FISCAL_TBL';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['PERIOD'], 'required'],
            [['PERIOD', 'YEAR', 'FISCAL'], 'string'],
            [['PERIOD'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'PERIOD' => 'P E R I O D',
            'YEAR' => 'Y E A R',
            'FISCAL' => 'F I S C A L',
        ];
    }




}
