<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.FOTOCOPY".
 *
 * @property integer $seq
 * @property string $machine_ip
 * @property string $job_type
 * @property string $user_name
 * @property string $color
 * @property string $job_name
 * @property string $completed_period
 * @property string $completed_date
 * @property string $completed_time
 * @property string $last_update
 * @property string $close_open
 * @property string $aliasModel
 */
abstract class FotocopyTbl extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.FOTOCOPY';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['machine_ip', 'job_type', 'user_name', 'color', 'job_name', 'completed_period', 'close_open'], 'string'],
            [['completed_date', 'completed_time', 'last_update'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'seq' => 'Seq',
            'machine_ip' => 'Machine Ip',
            'job_type' => 'Job Type',
            'user_name' => 'User Name',
            'color' => 'Color',
            'job_name' => 'Job Name',
            'completed_period' => 'Completed Period',
            'completed_date' => 'Completed Date',
            'completed_time' => 'Completed Time',
            'last_update' => 'Last Update',
            'close_open' => 'Close Open',
        ];
    }




}
