<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.GOJEK_VIEW_01".
 *
 * @property string $GOJEK_ID
 * @property string $GOJEK_DESC
 * @property integer $TIME_LOAD
 * @property integer $JOB_COUNT
 * @property string $ISSUE_PERIOD
 * @property string $ISSUE_DATE
 * @property string $STAT
 * @property integer $DAY_COUNT
 * @property string $min_date_time
 * @property string $max_date_time
 * @property double $TOTAL_LT
 * @property string $aliasModel
 */
abstract class GojekView01 extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.GOJEK_VIEW_01';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['GOJEK_ID', 'GOJEK_DESC', 'ISSUE_PERIOD', 'ISSUE_DATE', 'STAT'], 'string'],
            [['TIME_LOAD', 'DAY_COUNT'], 'required'],
            [['TIME_LOAD', 'JOB_COUNT', 'DAY_COUNT'], 'integer'],
            [['min_date_time', 'max_date_time'], 'safe'],
            [['TOTAL_LT'], 'number']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'GOJEK_ID' => 'Gojek  ID',
            'GOJEK_DESC' => 'Gojek  Desc',
            'TIME_LOAD' => 'Time  Load',
            'JOB_COUNT' => 'Job  Count',
            'ISSUE_PERIOD' => 'Issue  Period',
            'ISSUE_DATE' => 'Issue  Date',
            'STAT' => 'Stat',
            'DAY_COUNT' => 'Day  Count',
            'min_date_time' => 'Min Date Time',
            'max_date_time' => 'Max Date Time',
            'TOTAL_LT' => 'Total  Lt',
        ];
    }




}
