<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.GOJEK_TBL".
 *
 * @property string $GOJEK_ID
 * @property string $GOJEK_DESC
 * @property double $GOJEK_VALUE
 * @property string $from_loc
 * @property string $to_loc
 * @property string $STAGE
 * @property string $LAST_UPDATE
 * @property string $TERMINAL
 * @property string $TERMINAL_NAME
 * @property string $HADIR
 * @property string $SOURCE
 * @property string $beacon_id
 * @property string $uuid
 * @property string $major
 * @property string $minor
 * @property string $beacon_location
 * @property double $distance
 * @property string $beacon_last_update
 * @property string $aliasModel
 */
abstract class GojekTbl extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.GOJEK_TBL';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['GOJEK_ID'], 'required'],
            [['GOJEK_ID', 'GOJEK_DESC', 'from_loc', 'to_loc', 'STAGE', 'TERMINAL', 'TERMINAL_NAME', 'HADIR', 'SOURCE', 'beacon_id', 'uuid', 'major', 'minor', 'beacon_location'], 'string'],
            [['GOJEK_VALUE', 'distance'], 'number'],
            [['LAST_UPDATE', 'beacon_last_update'], 'safe'],
            [['GOJEK_ID'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'GOJEK_ID' => 'Gojek  ID',
            'GOJEK_DESC' => 'Gojek  Desc',
            'GOJEK_VALUE' => 'Gojek  Value',
            'from_loc' => 'From Loc',
            'to_loc' => 'To Loc',
            'STAGE' => 'Stage',
            'LAST_UPDATE' => 'Last  Update',
            'TERMINAL' => 'Terminal',
            'TERMINAL_NAME' => 'Terminal  Name',
            'HADIR' => 'Hadir',
            'SOURCE' => 'Source',
            'beacon_id' => 'Beacon ID',
            'uuid' => 'Uuid',
            'major' => 'Major',
            'minor' => 'Minor',
            'beacon_location' => 'Beacon Location',
            'distance' => 'Distance',
            'beacon_last_update' => 'Beacon Last Update',
        ];
    }




}
