<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.GOJEK_ORDER_REPORT".
 *
 * @property string $SequenceID
 * @property string $NIK
 * @property string $NAMA_KARYAWAN
 * @property string $period
 * @property string $post_date
 * @property string $StartTime
 * @property string $EndTime
 * @property double $Duration_available
 * @property double $Duration_gross
 * @property double $sisa_waktu_kerja
 * @property double $waktu_istirahat
 * @property double $Duration
 * @property double $iddle
 * @property double $waktu_istirahat_pct
 * @property double $Duration_pct
 * @property double $iddle_pct
 * @property string $TotalWorkhours
 * @property string $TotalBreaks
 * @property string $aliasModel
 */
abstract class GojekOrderReport extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.GOJEK_ORDER_REPORT';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['SequenceID', 'NIK', 'NAMA_KARYAWAN'], 'required'],
            [['SequenceID', 'NIK', 'NAMA_KARYAWAN', 'period', 'TotalWorkhours', 'TotalBreaks'], 'string'],
            [['post_date', 'StartTime', 'EndTime'], 'safe'],
            [['Duration_available', 'Duration_gross', 'sisa_waktu_kerja', 'waktu_istirahat', 'Duration', 'iddle', 'waktu_istirahat_pct', 'Duration_pct', 'iddle_pct'], 'number']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'SequenceID' => 'Sequence ID',
            'NIK' => 'Nik',
            'NAMA_KARYAWAN' => 'Nama  Karyawan',
            'period' => 'Period',
            'post_date' => 'Post Date',
            'StartTime' => 'Start Time',
            'EndTime' => 'End Time',
            'Duration_available' => 'Duration Available',
            'Duration_gross' => 'Duration Gross',
            'sisa_waktu_kerja' => 'Sisa Waktu Kerja',
            'waktu_istirahat' => 'Waktu Istirahat',
            'Duration' => 'Duration',
            'iddle' => 'Iddle',
            'waktu_istirahat_pct' => 'Waktu Istirahat Pct',
            'Duration_pct' => 'Duration Pct',
            'iddle_pct' => 'Iddle Pct',
            'TotalWorkhours' => 'Total Workhours',
            'TotalBreaks' => 'Total Breaks',
        ];
    }




}
