<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.GO_SA_TBL".
 *
 * @property integer $ID
 * @property string $REQUESTOR_NIK
 * @property string $REQUESTOR_NAME
 * @property string $START_TIME
 * @property string $END_TIME
 * @property string $REMARK
 * @property integer $TOTAL_MP
 * @property double $LT
 * @property integer $STATUS
 * @property integer $FLAG
 * @property string $aliasModel
 */
abstract class GoSaTbl extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.GO_SA_TBL';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['REQUESTOR_NIK', 'REQUESTOR_NAME', 'REMARK'], 'string'],
            [['START_TIME', 'END_TIME'], 'safe'],
            [['TOTAL_MP', 'STATUS', 'FLAG'], 'integer'],
            [['LT'], 'number']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ID' => 'ID',
            'REQUESTOR_NIK' => 'Requestor  Nik',
            'REQUESTOR_NAME' => 'Requestor  Name',
            'START_TIME' => 'Start  Time',
            'END_TIME' => 'End  Time',
            'REMARK' => 'Remark',
            'TOTAL_MP' => 'Total  Mp',
            'LT' => 'Lt',
            'STATUS' => 'Status',
            'FLAG' => 'Flag',
        ];
    }




}
