<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.GO_SA_TBL".
 *
 * @property integer $ID
 * @property string $GOJEK_ID
 * @property string $GOJEK_DESC
 * @property string $START_TIME
 * @property string $END_TIME
 * @property string $REMARK
 * @property integer $FLAG
 * @property string $aliasModel
 */
abstract class GoSaTbl extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.GO_SA_TBL';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ID', 'FLAG'], 'integer'],
            [['GOJEK_ID', 'GOJEK_DESC', 'REMARK'], 'string'],
            [['START_TIME', 'END_TIME'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ID' => 'ID',
            'GOJEK_ID' => 'Gojek  ID',
            'GOJEK_DESC' => 'Gojek  Desc',
            'START_TIME' => 'Start  Time',
            'END_TIME' => 'End  Time',
            'REMARK' => 'Remark',
            'FLAG' => 'Flag',
        ];
    }




}
