<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "tb_hak_akses".
 *
 * @property string $hak_akses
 * @property string $password_akses
 * @property string $level_akses
 * @property string $aliasModel
 */
abstract class HakAkses extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tb_hak_akses';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_mis7');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['hak_akses', 'password_akses', 'level_akses'], 'required'],
            [['hak_akses', 'password_akses'], 'string', 'max' => 30],
            [['level_akses'], 'string', 'max' => 5],
            [['hak_akses'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'hak_akses' => 'Hak Akses',
            'password_akses' => 'Password Akses',
            'level_akses' => 'Level Akses',
        ];
    }




}
