<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.HR_COMPLAINT".
 *
 * @property integer $id
 * @property string $period
 * @property string $input_datetime
 * @property string $nik
 * @property string $emp_name
 * @property string $department
 * @property string $section
 * @property string $sub_section
 * @property string $remark
 * @property string $remark_category
 * @property string $response
 * @property string $response_datetime
 * @property integer $status
 * @property string $category
 * @property string $client_ip
 * @property string $whatsapp
 * @property string $aliasModel
 */
abstract class HrComplaint extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.HR_COMPLAINT';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['input_datetime', 'response_datetime'], 'safe'],
            [['remark', 'response'], 'string'],
            [['status'], 'integer'],
            [['period'], 'string', 'max' => 6],
            [['nik'], 'string', 'max' => 10],
            [['emp_name'], 'string', 'max' => 150],
            [['department', 'section', 'sub_section', 'remark_category', 'category'], 'string', 'max' => 50],
            [['client_ip'], 'string', 'max' => 250],
            [['whatsapp'], 'string', 'max' => 1]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'period' => 'Period',
            'input_datetime' => 'Input Datetime',
            'nik' => 'Nik',
            'emp_name' => 'Emp Name',
            'department' => 'Department',
            'section' => 'Section',
            'sub_section' => 'Sub Section',
            'remark' => 'Remark',
            'remark_category' => 'Remark Category',
            'response' => 'Response',
            'response_datetime' => 'Response Datetime',
            'status' => 'Status',
            'category' => 'Category',
            'client_ip' => 'Client Ip',
            'whatsapp' => 'Whatsapp',
        ];
    }




}
