<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "tbl_drug_master".
 *
 * @property string $drug_master_partnumb
 * @property string $drug_master_partname
 * @property string $drug_master_category
 * @property string $drug_master_unit_using
 * @property integer $drug_master_status_using
 * @property string $drug_master_unit_packet
 * @property string $drug_master_qty_packet
 * @property double $drug_master_price
 * @property string $aliasModel
 */
abstract class HrgaDrugMaster extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tbl_drug_master';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_hrga_dev');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['drug_master_partnumb', 'drug_master_partname', 'drug_master_category', 'drug_master_unit_using', 'drug_master_status_using', 'drug_master_unit_packet', 'drug_master_qty_packet', 'drug_master_price'], 'required'],
            [['drug_master_status_using'], 'integer'],
            [['drug_master_price'], 'number'],
            [['drug_master_partnumb', 'drug_master_partname', 'drug_master_category', 'drug_master_unit_using', 'drug_master_unit_packet', 'drug_master_qty_packet'], 'string', 'max' => 100],
            [['drug_master_partnumb'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'drug_master_partnumb' => 'Drug Master Partnumb',
            'drug_master_partname' => 'Drug Master Partname',
            'drug_master_category' => 'Drug Master Category',
            'drug_master_unit_using' => 'Drug Master Unit Using',
            'drug_master_status_using' => 'Drug Master Status Using',
            'drug_master_unit_packet' => 'Drug Master Unit Packet',
            'drug_master_qty_packet' => 'Drug Master Qty Packet',
            'drug_master_price' => 'Drug Master Price',
        ];
    }




}
