<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.IJAZAH_ITEM".
 *
 * @property string $ITEM
 * @property string $ITEM_DESC
 * @property string $DESTINATION
 * @property string $PRODUCT_TYPE
 * @property string $BU
 * @property string $BU_SAP
 * @property string $FG_KD
 * @property string $MODEL
 * @property string $LINE
 * @property string $aliasModel
 */
abstract class IjazahItem extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.IJAZAH_ITEM';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ITEM'], 'required'],
            [['ITEM'], 'string', 'max' => 11],
            [['ITEM_DESC', 'DESTINATION', 'PRODUCT_TYPE', 'BU', 'BU_SAP', 'FG_KD', 'MODEL'], 'string', 'max' => 50],
            [['LINE'], 'string', 'max' => 20],
            [['ITEM'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ITEM' => 'Item',
            'ITEM_DESC' => 'Item Desc',
            'DESTINATION' => 'Destination',
            'PRODUCT_TYPE' => 'Product Type',
            'BU' => 'Bu',
            'BU_SAP' => 'Bu Sap',
            'FG_KD' => 'Fg Kd',
            'MODEL' => 'Model',
            'LINE' => 'Line',
        ];
    }




}
