<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.INJ_MACHINE_MOLDING_LOG".
 *
 * @property string $ID
 * @property string $POST_DATE
 * @property string $PERIOD
 * @property string $MACHINE_ID
 * @property string $MACHINE_DESC
 * @property string $MOLDING_ID
 * @property string $MOLDING_NAME
 * @property string $ITEM
 * @property string $ITEM_DESC
 * @property string $COLOR_STATUS
 * @property string $START_TIME
 * @property string $END_TIME
 * @property integer $TOTAL_TIME_SECOND
 * @property string $aliasModel
 */
abstract class InjMachineMoldingLog extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.INJ_MACHINE_MOLDING_LOG';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ID'], 'required'],
            [['POST_DATE', 'START_TIME', 'END_TIME'], 'safe'],
            [['TOTAL_TIME_SECOND'], 'integer'],
            [['ID', 'MACHINE_ID', 'MOLDING_ID', 'ITEM', 'COLOR_STATUS'], 'string', 'max' => 50],
            [['PERIOD'], 'string', 'max' => 10],
            [['MACHINE_DESC', 'ITEM_DESC'], 'string', 'max' => 250],
            [['MOLDING_NAME'], 'string', 'max' => 150],
            [['ID'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ID' => 'ID',
            'POST_DATE' => 'Post Date',
            'PERIOD' => 'Period',
            'MACHINE_ID' => 'Machine ID',
            'MACHINE_DESC' => 'Machine Desc',
            'MOLDING_ID' => 'Molding ID',
            'MOLDING_NAME' => 'Molding Name',
            'ITEM' => 'Item',
            'ITEM_DESC' => 'Item Desc',
            'COLOR_STATUS' => 'Color Status',
            'START_TIME' => 'Start Time',
            'END_TIME' => 'End Time',
            'TOTAL_TIME_SECOND' => 'Total Time Second',
        ];
    }




}
