<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.INJ_MACHINE_TBL".
 *
 * @property string $MACHINE_ID
 * @property string $MACHINE_DESC
 * @property string $MOULDING_ID
 * @property string $MOULDING_NAME
 * @property integer $TOTAL_COUNT
 * @property string $LAST_UPDATE
 * @property string $aliasModel
 */
abstract class InjMachineTbl extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.INJ_MACHINE_TBL';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['MACHINE_ID'], 'required'],
            [['TOTAL_COUNT'], 'integer'],
            [['LAST_UPDATE'], 'safe'],
            [['MACHINE_ID', 'MOULDING_ID'], 'string', 'max' => 50],
            [['MACHINE_DESC'], 'string', 'max' => 250],
            [['MOULDING_NAME'], 'string', 'max' => 150],
            [['MACHINE_ID'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'MACHINE_ID' => 'Machine ID',
            'MACHINE_DESC' => 'Machine Desc',
            'MOULDING_ID' => 'Moulding ID',
            'MOULDING_NAME' => 'Moulding Name',
            'TOTAL_COUNT' => 'Total Count',
            'LAST_UPDATE' => 'Last Update',
        ];
    }




}
