<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.ITEM_UNCOUNTTABLE".
 *
 * @property string $POST_DATE_ITEM
 * @property string $POST_DATE
 * @property string $ITEM
 * @property string $ITEM_DESC
 * @property string $ITEM_UM
 * @property string $SUPPLIER
 * @property string $SUPPLIER_DESC
 * @property string $KELOMPOK
 * @property string $TIPE
 * @property double $MAT_SAP
 * @property double $MAT_WSUS
 * @property double $MAT_DIFF
 * @property double $WIP_SAP
 * @property double $WIP_PI
 * @property double $WIP_DIFF
 * @property double $WIP_DIFF_ABS
 * @property double $TOT_SAP
 * @property double $TOT_WSUS_PI
 * @property double $TOT_DIFF
 * @property double $STD_PRICE
 * @property double $WIP_SAP_AMT
 * @property double $WIP_PI_AMT
 * @property double $WIP_DIFF_AMT
 * @property double $WIP_DIFF_ABS_AMT
 * @property string $SHOW
 * @property string $aliasModel
 */
abstract class ItemUncounttable extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.ITEM_UNCOUNTTABLE';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['POST_DATE_ITEM'], 'required'],
            [['POST_DATE_ITEM', 'ITEM', 'ITEM_DESC', 'ITEM_UM', 'SUPPLIER', 'SUPPLIER_DESC', 'KELOMPOK', 'TIPE', 'SHOW'], 'string'],
            [['POST_DATE'], 'safe'],
            [['MAT_SAP', 'MAT_WSUS', 'MAT_DIFF', 'WIP_SAP', 'WIP_PI', 'WIP_DIFF', 'WIP_DIFF_ABS', 'TOT_SAP', 'TOT_WSUS_PI', 'TOT_DIFF', 'STD_PRICE', 'WIP_SAP_AMT', 'WIP_PI_AMT', 'WIP_DIFF_AMT', 'WIP_DIFF_ABS_AMT'], 'number'],
            [['POST_DATE_ITEM'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'POST_DATE_ITEM' => 'Post  Date  Item',
            'POST_DATE' => 'Post  Date',
            'ITEM' => 'Item',
            'ITEM_DESC' => 'Item  Desc',
            'ITEM_UM' => 'Item  Um',
            'SUPPLIER' => 'Supplier',
            'SUPPLIER_DESC' => 'Supplier  Desc',
            'KELOMPOK' => 'Kelompok',
            'TIPE' => 'Tipe',
            'MAT_SAP' => 'Mat  Sap',
            'MAT_WSUS' => 'Mat  Wsus',
            'MAT_DIFF' => 'Mat  Diff',
            'WIP_SAP' => 'Wip  Sap',
            'WIP_PI' => 'Wip  Pi',
            'WIP_DIFF' => 'Wip  Diff',
            'WIP_DIFF_ABS' => 'Wip  Diff  Abs',
            'TOT_SAP' => 'Tot  Sap',
            'TOT_WSUS_PI' => 'Tot  Wsus  Pi',
            'TOT_DIFF' => 'Tot  Diff',
            'STD_PRICE' => 'Std  Price',
            'WIP_SAP_AMT' => 'Wip  Sap  Amt',
            'WIP_PI_AMT' => 'Wip  Pi  Amt',
            'WIP_DIFF_AMT' => 'Wip  Diff  Amt',
            'WIP_DIFF_ABS_AMT' => 'Wip  Diff  Abs  Amt',
            'SHOW' => 'Show',
        ];
    }




}
