<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.KANBAN_FLOW_HDR".
 *
 * @property string $job_flow_id
 * @property string $job_flow_desc
 * @property integer $job_flow_line
 * @property string $user_id
 * @property string $user_desc
 * @property string $last_update
 * @property string $aliasModel
 */
abstract class KanbanFlowHdr extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.KANBAN_FLOW_HDR';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['job_flow_id', 'job_flow_desc'], 'required'],
            [['job_flow_line'], 'integer'],
            [['last_update'], 'safe'],
            [['job_flow_id', 'job_flow_desc', 'user_id', 'user_desc'], 'string', 'max' => 50],
            [['job_flow_id'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'job_flow_id' => 'Job Flow ID',
            'job_flow_desc' => 'Job Flow Desc',
            'job_flow_line' => 'Job Flow Line',
            'user_id' => 'User ID',
            'user_desc' => 'User Desc',
            'last_update' => 'Last Update',
        ];
    }




}
