<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.KANBAN_PCH_LOG".
 *
 * @property string $seq
 * @property string $period
 * @property string $vendor_code
 * @property string $vendor_name
 * @property string $voucher_no
 * @property string $invoice_act
 * @property string $do
 * @property string $currency
 * @property double $amount
 * @property string $pic
 * @property string $division
 * @property string $source_data
 * @property string $term
 * @property double $request
 * @property double $in_progress
 * @property string $finance_rcv
 * @property double $done
 * @property double $count_stat
 * @property string $stage
 * @property string $last_update
 * @property string $aliasModel
 */
abstract class KanbanPchLog extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.KANBAN_PCH_LOG';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['amount', 'request', 'in_progress', 'done', 'count_stat'], 'number'],
            [['last_update'], 'safe'],
            [['period', 'vendor_code'], 'string', 'max' => 8],
            [['vendor_name', 'voucher_no', 'invoice_act', 'do', 'pic', 'division', 'source_data', 'term', 'stage'], 'string', 'max' => 50],
            [['currency'], 'string', 'max' => 10],
            [['finance_rcv'], 'string', 'max' => 6]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'seq' => 'Seq',
            'period' => 'Period',
            'vendor_code' => 'Vendor Code',
            'vendor_name' => 'Vendor Name',
            'voucher_no' => 'Voucher No',
            'invoice_act' => 'Invoice Act',
            'do' => 'Do',
            'currency' => 'Currency',
            'amount' => 'Amount',
            'pic' => 'Pic',
            'division' => 'Division',
            'source_data' => 'Source Data',
            'term' => 'Term',
            'request' => 'Request',
            'in_progress' => 'In Progress',
            'finance_rcv' => 'Finance Rcv',
            'done' => 'Done',
            'count_stat' => 'Count Stat',
            'stage' => 'Stage',
            'last_update' => 'Last Update',
        ];
    }




}
