<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "dbo.KOYEMI_IN_OUT_VIEW".
 *
 * @property string $tgl
 * @property string $user_name
 * @property string $in_out_status
 * @property string $in_out_datetime
 * @property string $aliasModel
 */
abstract class KoyemiInOutView extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'dbo.KOYEMI_IN_OUT_VIEW';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_biostar_tna');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['in_out_datetime'], 'safe'],
            [['tgl'], 'string', 'max' => 4000],
            [['user_name', 'in_out_status'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'tgl' => 'Tgl',
            'user_name' => 'User Name',
            'in_out_status' => 'In Out Status',
            'in_out_datetime' => 'In Out Datetime',
        ];
    }




}
