<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.LIVE_COOKING_LIST".
 *
 * @property string $cc
 * @property string $cc_desc
 * @property string $type
 * @property integer $budget
 * @property string $aliasModel
 */
abstract class LiveCookingList extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.LIVE_COOKING_LIST';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['cc'], 'required'],
            [['cc', 'cc_desc', 'type'], 'string'],
            [['budget'], 'integer'],
            [['cc'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'cc' => 'Cc',
            'cc_desc' => 'Cc Desc',
            'type' => 'Type',
            'budget' => 'Budget',
        ];
    }




}
