<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.LOC_ITEM_TBL".
 *
 * @property string $LOC_ITEM
 * @property string $LOC
 * @property string $ITEM_EQ
 * @property double $ONHAND
 * @property string $aliasModel
 */
abstract class LocItemTbl extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.LOC_ITEM_TBL';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_wsus');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['LOC_ITEM'], 'required'],
            [['LOC_ITEM', 'LOC', 'ITEM_EQ'], 'string'],
            [['ONHAND'], 'number'],
            [['LOC_ITEM'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'LOC_ITEM' => 'Loc  Item',
            'LOC' => 'Loc',
            'ITEM_EQ' => 'Item  Eq',
            'ONHAND' => 'Onhand',
        ];
    }




}
