<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.MACHINE_IOT_CURRENT_EFF".
 *
 * @property string $trans_id
 * @property string $mesin_id
 * @property string $mesin_description
 * @property string $posting_date
 * @property string $period_shift
 * @property string $posting_shift
 * @property string $seq
 * @property integer $shift
 * @property integer $jam
 * @property double $merah
 * @property double $kuning
 * @property double $hijau
 * @property double $biru
 * @property double $putih
 * @property double $lost_data
 * @property double $total
 * @property double $hijau_biru
 * @property double $pct
 * @property string $eff_stat
 * @property string $last_update
 * @property string $aliasModel
 */
abstract class MachineIotCurrentEff extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.MACHINE_IOT_CURRENT_EFF';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['trans_id'], 'required'],
            [['trans_id', 'mesin_id', 'mesin_description', 'period_shift', 'seq', 'eff_stat'], 'string'],
            [['posting_date', 'posting_shift', 'last_update'], 'safe'],
            [['shift', 'jam'], 'integer'],
            [['merah', 'kuning', 'hijau', 'biru', 'putih', 'lost_data', 'total', 'hijau_biru', 'pct'], 'number'],
            [['trans_id'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'trans_id' => 'Trans ID',
            'mesin_id' => 'Mesin ID',
            'mesin_description' => 'Mesin Description',
            'posting_date' => 'Posting Date',
            'period_shift' => 'Period Shift',
            'posting_shift' => 'Posting Shift',
            'seq' => 'Seq',
            'shift' => 'Shift',
            'jam' => 'Jam',
            'merah' => 'Merah',
            'kuning' => 'Kuning',
            'hijau' => 'Hijau',
            'biru' => 'Biru',
            'putih' => 'Putih',
            'lost_data' => 'Lost Data',
            'total' => 'Total',
            'hijau_biru' => 'Hijau Biru',
            'pct' => 'Pct',
            'eff_stat' => 'Eff Stat',
            'last_update' => 'Last Update',
        ];
    }




}
