<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.MACHINE_KWH_REPORT".
 *
 * @property string $period
 * @property integer $week_number
 * @property string $posting_date
 * @property string $mesin_id
 * @property string $mesin_description
 * @property integer $jam_no
 * @property double $start_kwh
 * @property double $end_kwh
 * @property double $power_consumption
 * @property string $aliasModel
 */
abstract class MachineKwhReport extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.MACHINE_KWH_REPORT';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['period', 'mesin_id', 'mesin_description'], 'string'],
            [['week_number', 'jam_no'], 'integer'],
            [['posting_date'], 'safe'],
            [['start_kwh', 'end_kwh', 'power_consumption'], 'number']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'period' => 'Period',
            'week_number' => 'Week Number',
            'posting_date' => 'Posting Date',
            'mesin_id' => 'Mesin ID',
            'mesin_description' => 'Mesin Description',
            'jam_no' => 'Jam No',
            'start_kwh' => 'Start Kwh',
            'end_kwh' => 'End Kwh',
            'power_consumption' => 'Power Consumption',
        ];
    }




}
