<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.MACHINE_IOT_AVAILABILITY_EFF_02".
 *
 * @property string $period
 * @property integer $week_number
 * @property string $posting_date
 * @property string $mesin_id
 * @property string $mesin_description
 * @property double $total_putih
 * @property double $total_hijau
 * @property double $total_biru
 * @property double $total_merah
 * @property double $total_unknown
 * @property double $availability
 * @property double $efficiency
 * @property string $aliasModel
 */
abstract class MachineIotAvailabilityEff02 extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.MACHINE_IOT_AVAILABILITY_EFF_02';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['period', 'mesin_id', 'mesin_description'], 'string'],
            [['week_number'], 'integer'],
            [['posting_date'], 'safe'],
            [['total_putih', 'total_hijau', 'total_biru', 'total_merah', 'total_unknown', 'availability', 'efficiency'], 'number']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'period' => 'Period',
            'week_number' => 'Week Number',
            'posting_date' => 'Posting Date',
            'mesin_id' => 'Mesin ID',
            'mesin_description' => 'Mesin Description',
            'total_putih' => 'Total Putih',
            'total_hijau' => 'Total Hijau',
            'total_biru' => 'Total Biru',
            'total_merah' => 'Total Merah',
            'total_unknown' => 'Total Unknown',
            'availability' => 'Availability',
            'efficiency' => 'Efficiency',
        ];
    }




}
