<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.MACHINE_IOT".
 *
 * @property string $sequence_number
 * @property string $mesin_id
 * @property string $mesin_description
 * @property double $arus_r
 * @property double $arus_s
 * @property double $arus_t
 * @property double $tegangan_r
 * @property double $tegangan_s
 * @property double $tegangan_t
 * @property double $power_factor
 * @property double $kw
 * @property double $kwh
 * @property double $harmonic_tegangan_v
 * @property double $harmonic_tegangan_pct
 * @property double $harmonic_arus_a
 * @property double $harmonic_arus_pct
 * @property double $frequency
 * @property integer $merah
 * @property integer $kuning
 * @property integer $hijau
 * @property integer $biru
 * @property integer $putih
 * @property string $status_warna
 * @property string $period
 * @property integer $week_number
 * @property string $posting_date
 * @property integer $posting_day_number
 * @property string $posting_time
 * @property string $system_date_time
 * @property integer $jam_no
 * @property integer $menit_no
 * @property integer $detik_no
 * @property double $count
 * @property string $aliasModel
 */
abstract class MachineIot extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.MACHINE_IOT';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['mesin_id', 'mesin_description', 'status_warna', 'period'], 'string'],
            [['arus_r', 'arus_s', 'arus_t', 'tegangan_r', 'tegangan_s', 'tegangan_t', 'power_factor', 'kw', 'kwh', 'harmonic_tegangan_v', 'harmonic_tegangan_pct', 'harmonic_arus_a', 'harmonic_arus_pct', 'frequency', 'count'], 'number'],
            [['merah', 'kuning', 'hijau', 'biru', 'putih', 'week_number', 'posting_day_number', 'jam_no', 'menit_no', 'detik_no'], 'integer'],
            [['posting_date', 'posting_time', 'system_date_time'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'sequence_number' => 'Sequence Number',
            'mesin_id' => 'Mesin ID',
            'mesin_description' => 'Mesin Description',
            'arus_r' => 'Arus R',
            'arus_s' => 'Arus S',
            'arus_t' => 'Arus T',
            'tegangan_r' => 'Tegangan R',
            'tegangan_s' => 'Tegangan S',
            'tegangan_t' => 'Tegangan T',
            'power_factor' => 'Power Factor',
            'kw' => 'Kw',
            'kwh' => 'Kwh',
            'harmonic_tegangan_v' => 'Harmonic Tegangan V',
            'harmonic_tegangan_pct' => 'Harmonic Tegangan Pct',
            'harmonic_arus_a' => 'Harmonic Arus A',
            'harmonic_arus_pct' => 'Harmonic Arus Pct',
            'frequency' => 'Frequency',
            'merah' => 'Merah',
            'kuning' => 'Kuning',
            'hijau' => 'Hijau',
            'biru' => 'Biru',
            'putih' => 'Putih',
            'status_warna' => 'Status Warna',
            'period' => 'Period',
            'week_number' => 'Week Number',
            'posting_date' => 'Posting Date',
            'posting_day_number' => 'Posting Day Number',
            'posting_time' => 'Posting Time',
            'system_date_time' => 'System Date Time',
            'jam_no' => 'Jam No',
            'menit_no' => 'Menit No',
            'detik_no' => 'Detik No',
            'count' => 'Count',
        ];
    }




}
