<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.MACHINE_IOT_CURRENT".
 *
 * @property string $mesin_id
 * @property string $mesin_description
 * @property string $status_warna
 * @property string $system_date_time
 * @property string $aliasModel
 */
abstract class MachineIotCurrent extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.MACHINE_IOT_CURRENT';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['mesin_id'], 'required'],
            [['mesin_id', 'mesin_description', 'status_warna'], 'string'],
            [['system_date_time'], 'safe'],
            [['mesin_id'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'mesin_id' => 'Mesin ID',
            'mesin_description' => 'Mesin Description',
            'status_warna' => 'Status Warna',
            'system_date_time' => 'System Date Time',
        ];
    }




}
