<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.MACHINE_IOT_OUTPUT".
 *
 * @property integer $seq
 * @property string $mesin_id
 * @property string $mesin_description
 * @property string $kelompok
 * @property string $lot_number
 * @property string $model_group
 * @property string $parent
 * @property string $parent_desc
 * @property string $gmc
 * @property string $gmc_desc
 * @property double $lot_qty
 * @property double $ng_qty
 * @property string $start_date
 * @property string $end_date
 * @property string $posting_shift
 * @property integer $shift
 * @property integer $lama_proses
 * @property integer $man_power_qty
 * @property string $man_power_name
 * @property string $start_by_id
 * @property string $start_by_name
 * @property string $end_by_id
 * @property string $end_by_name
 * @property string $minor
 * @property string $aliasModel
 */
abstract class MachineIotOutput extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.MACHINE_IOT_OUTPUT';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['mesin_id'], 'required'],
            [['lot_qty', 'ng_qty'], 'number'],
            [['start_date', 'end_date', 'posting_shift'], 'safe'],
            [['shift', 'lama_proses', 'man_power_qty'], 'integer'],
            [['man_power_name'], 'string'],
            [['mesin_id', 'kelompok', 'lot_number', 'model_group', 'gmc_desc', 'minor'], 'string', 'max' => 50],
            [['mesin_description'], 'string', 'max' => 100],
            [['parent', 'start_by_id', 'end_by_id'], 'string', 'max' => 20],
            [['parent_desc', 'start_by_name', 'end_by_name'], 'string', 'max' => 250],
            [['gmc'], 'string', 'max' => 11]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'seq' => 'Seq',
            'mesin_id' => 'Mesin ID',
            'mesin_description' => 'Mesin Description',
            'kelompok' => 'Kelompok',
            'lot_number' => 'Lot Number',
            'model_group' => 'Model Group',
            'parent' => 'Parent',
            'parent_desc' => 'Parent Desc',
            'gmc' => 'Gmc',
            'gmc_desc' => 'Gmc Desc',
            'lot_qty' => 'Lot Qty',
            'ng_qty' => 'Ng Qty',
            'start_date' => 'Start Date',
            'end_date' => 'End Date',
            'posting_shift' => 'Posting Shift',
            'shift' => 'Shift',
            'lama_proses' => 'Lama Proses',
            'man_power_qty' => 'Man Power Qty',
            'man_power_name' => 'Man Power Name',
            'start_by_id' => 'Start By ID',
            'start_by_name' => 'Start By Name',
            'end_by_id' => 'End By ID',
            'end_by_name' => 'End By Name',
            'minor' => 'Minor',
        ];
    }




}
