<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "tbl_barang_out".
 *
 * @property integer $id_barang_out
 * @property string $slip_out
 * @property string $part_no
 * @property string $part_name
 * @property string $category
 * @property string $exp_out
 * @property string $serno_out
 * @property double $jml_out
 * @property string $satuan_out
 * @property string $note_out
 * @property string $datetime_out
 * @property string $starttime_out
 * @property string $endtime_out
 * @property double $totaltime_out
 * @property string $requestor_nik
 * @property string $requestor_name
 * @property string $requestor_dept
 * @property string $requestor_sec
 * @property string $requestor_before
 * @property integer $stts_out
 * @property integer $stts_outstanding
 * @property string $approve_by
 * @property string $datetime_approve
 * @property string $aliasModel
 */
abstract class MaskerPrdOut extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tbl_barang_out';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_cbsupplement');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['slip_out', 'part_no', 'part_name', 'category', 'serno_out', 'jml_out', 'satuan_out', 'note_out', 'datetime_out', 'requestor_nik', 'requestor_name', 'requestor_dept', 'requestor_before', 'stts_out', 'stts_outstanding', 'approve_by'], 'required'],
            [['exp_out', 'datetime_out', 'starttime_out', 'endtime_out', 'datetime_approve'], 'safe'],
            [['jml_out', 'totaltime_out'], 'number'],
            [['stts_out', 'stts_outstanding'], 'integer'],
            [['slip_out', 'part_no', 'part_name', 'category', 'serno_out', 'satuan_out', 'note_out', 'requestor_nik', 'requestor_name', 'requestor_dept', 'requestor_sec', 'requestor_before', 'approve_by'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_barang_out' => 'Id Barang Out',
            'slip_out' => 'Slip Out',
            'part_no' => 'Part No',
            'part_name' => 'Part Name',
            'category' => 'Category',
            'exp_out' => 'Exp Out',
            'serno_out' => 'Serno Out',
            'jml_out' => 'Jml Out',
            'satuan_out' => 'Satuan Out',
            'note_out' => 'Note Out',
            'datetime_out' => 'Datetime Out',
            'starttime_out' => 'Starttime Out',
            'endtime_out' => 'Endtime Out',
            'totaltime_out' => 'Totaltime Out',
            'requestor_nik' => 'Requestor Nik',
            'requestor_name' => 'Requestor Name',
            'requestor_dept' => 'Requestor Dept',
            'requestor_sec' => 'Requestor Sec',
            'requestor_before' => 'Requestor Before',
            'stts_out' => 'Stts Out',
            'stts_outstanding' => 'Stts Outstanding',
            'approve_by' => 'Approve By',
            'datetime_approve' => 'Datetime Approve',
        ];
    }




}
