<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "tb_barang".
 *
 * @property integer $id
 * @property string $namamasker
 * @property string $qty
 * @property string $aliasModel
 */
abstract class MaskerStock extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tb_barang';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_recordmasker');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['namamasker', 'qty'], 'required'],
            [['namamasker', 'qty'], 'string', 'max' => 30]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'namamasker' => 'Namamasker',
            'qty' => 'Qty',
        ];
    }




}
