<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "tb_incoming".
 *
 * @property integer $pk
 * @property string $tgl
 * @property string $part_number
 * @property double $plan
 * @property double $qty
 * @property string $tgl_exp
 * @property string $aliasModel
 */
abstract class MaskerPrdIn extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tb_incoming';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_cbsupplement');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['tgl', 'tgl_exp'], 'safe'],
            [['plan', 'qty'], 'number'],
            [['part_number'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'pk' => 'Pk',
            'tgl' => 'Tgl',
            'part_number' => 'Part Number',
            'plan' => 'Plan',
            'qty' => 'Qty',
            'tgl_exp' => 'Tgl Exp',
        ];
    }




}
