<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "tb_barang".
 *
 * @property string $part_no
 * @property string $part_name
 * @property double $min
 * @property double $max
 * @property string $satuan
 * @property string $grup
 * @property string $sec
 * @property string $rack
 * @property string $aliasModel
 */
abstract class MaskerPrdData extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tb_barang';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_cbsupplement');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['part_no', 'part_name', 'min', 'max', 'satuan', 'rack'], 'required'],
            [['min', 'max'], 'number'],
            [['part_no', 'part_name', 'satuan', 'sec', 'rack'], 'string', 'max' => 100],
            [['grup'], 'string', 'max' => 50],
            [['part_no'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'part_no' => 'Part No',
            'part_name' => 'Part Name',
            'min' => 'Min',
            'max' => 'Max',
            'satuan' => 'Satuan',
            'grup' => 'Grup',
            'sec' => 'Sec',
            'rack' => 'Rack',
        ];
    }




}
