<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "tbl_barang_in".
 *
 * @property integer $id_barang_in
 * @property string $part_no
 * @property string $part_name
 * @property string $category
 * @property string $exp_date
 * @property string $serno
 * @property double $qty_in
 * @property double $qty_stock
 * @property string $datetime_in
 * @property string $aliasModel
 */
abstract class MaskerPrdStock extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tbl_barang_in';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_cbsupplement');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['part_no', 'part_name', 'category', 'serno', 'qty_in', 'qty_stock', 'datetime_in'], 'required'],
            [['exp_date', 'datetime_in'], 'safe'],
            [['qty_in', 'qty_stock'], 'number'],
            [['part_no', 'part_name', 'category', 'serno'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_barang_in' => 'Id Barang In',
            'part_no' => 'Part No',
            'part_name' => 'Part Name',
            'category' => 'Category',
            'exp_date' => 'Exp Date',
            'serno' => 'Serno',
            'qty_in' => 'Qty In',
            'qty_stock' => 'Qty Stock',
            'datetime_in' => 'Datetime In',
        ];
    }




}
