<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "meeting_event".
 *
 * @property integer $id
 * @property integer $start_time
 * @property integer $end_time
 * @property string $tgl_jam_start
 * @property string $tgl_start
 * @property string $jam_start
 * @property string $tgl_jam_end
 * @property string $tgl_end
 * @property string $jam_end
 * @property integer $room_id
 * @property string $room_name
 * @property string $name
 * @property string $description
 * @property string $meeting_status
 * @property string $aliasModel
 */
abstract class MeetingEvent extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'meeting_event';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_mrbs');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'start_time', 'end_time', 'room_id'], 'integer'],
            [['tgl_jam_start', 'tgl_start', 'jam_start', 'tgl_jam_end', 'tgl_end', 'jam_end'], 'safe'],
            [['description'], 'string'],
            [['room_name'], 'string', 'max' => 25],
            [['name'], 'string', 'max' => 500],
            [['meeting_status'], 'string', 'max' => 1]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'start_time' => 'Start Time',
            'end_time' => 'End Time',
            'tgl_jam_start' => 'Tgl Jam Start',
            'tgl_start' => 'Tgl Start',
            'jam_start' => 'Jam Start',
            'tgl_jam_end' => 'Tgl Jam End',
            'tgl_end' => 'Tgl End',
            'jam_end' => 'Jam End',
            'room_id' => 'Room ID',
            'room_name' => 'Room Name',
            'name' => 'Name',
            'description' => 'Description',
            'meeting_status' => 'Meeting Status',
        ];
    }




}
