<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.MESIN_NG_FREQ_04".
 *
 * @property string $periode_kerusakan
 * @property string $tgl_kerusakan
 * @property string $mesin_id
 * @property integer $freq_kerusakan
 * @property integer $jumlah_kerusakan
 * @property integer $lama_perbaikan_menit
 * @property string $aliasModel
 */
abstract class MesinNgFreq04 extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.MESIN_NG_FREQ_04';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['periode_kerusakan', 'tgl_kerusakan', 'mesin_id'], 'string'],
            [['freq_kerusakan', 'jumlah_kerusakan', 'lama_perbaikan_menit'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'periode_kerusakan' => 'Periode Kerusakan',
            'tgl_kerusakan' => 'Tgl Kerusakan',
            'mesin_id' => 'Mesin ID',
            'freq_kerusakan' => 'Freq Kerusakan',
            'jumlah_kerusakan' => 'Jumlah Kerusakan',
            'lama_perbaikan_menit' => 'Lama Perbaikan Menit',
        ];
    }




}
