<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.MESIN_CHECK_TBL".
 *
 * @property integer $urutan
 * @property string $mesin_id
 * @property string $mesin_nama
 * @property string $mesin_no
 * @property string $mesin_bagian
 * @property string $mesin_bagian_ket
 * @property string $mesin_status
 * @property string $mesin_catatan
 * @property string $mesin_periode
 * @property string $aliasModel
 */
abstract class MesinCheckTbl extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.MESIN_CHECK_TBL';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['mesin_id', 'mesin_nama', 'mesin_no', 'mesin_bagian', 'mesin_bagian_ket', 'mesin_status', 'mesin_catatan', 'mesin_periode'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'urutan' => 'Urutan',
            'mesin_id' => 'Mesin ID',
            'mesin_nama' => 'Mesin Nama',
            'mesin_no' => 'Mesin No',
            'mesin_bagian' => 'Mesin Bagian',
            'mesin_bagian_ket' => 'Mesin Bagian Ket',
            'mesin_status' => 'Mesin Status',
            'mesin_catatan' => 'Mesin Catatan',
            'mesin_periode' => 'Mesin Periode',
        ];
    }




}
