<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.MESIN_CHECK_RESULT_01".
 *
 * @property string $post_date
 * @property integer $urutan
 * @property string $location
 * @property string $area
 * @property string $mesin_id
 * @property string $mesin_nama
 * @property string $mesin_no
 * @property string $mesin_bagian
 * @property string $mesin_bagian_ket
 * @property string $mesin_status
 * @property string $mesin_catatan
 * @property string $mesin_periode
 * @property string $user_id
 * @property string $user_desc
 * @property string $mesin_last_update
 * @property integer $hasil_ok
 * @property integer $hasil_ng
 * @property integer $total_cek
 * @property string $aliasModel
 */
abstract class MesinCheckResult01 extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.MESIN_CHECK_RESULT_01';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['post_date', 'mesin_last_update'], 'safe'],
            [['mesin_catatan'], 'string'],
            [['hasil_ok', 'hasil_ng', 'total_cek'], 'integer'],
            [['location', 'area', 'user_desc'], 'string', 'max' => 50],
            [['mesin_id', 'mesin_status', 'user_id'], 'string', 'max' => 10],
            [['mesin_nama', 'mesin_bagian', 'mesin_bagian_ket'], 'string', 'max' => 100],
            [['mesin_no'], 'string', 'max' => 3],
            [['mesin_periode'], 'string', 'max' => 30]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'post_date' => 'Post Date',
            'urutan' => 'Urutan',
            'location' => 'Location',
            'area' => 'Area',
            'mesin_id' => 'Mesin ID',
            'mesin_nama' => 'Mesin Nama',
            'mesin_no' => 'Mesin No',
            'mesin_bagian' => 'Mesin Bagian',
            'mesin_bagian_ket' => 'Mesin Bagian Ket',
            'mesin_status' => 'Mesin Status',
            'mesin_catatan' => 'Mesin Catatan',
            'mesin_periode' => 'Mesin Periode',
            'user_id' => 'User ID',
            'user_desc' => 'User Desc',
            'mesin_last_update' => 'Mesin Last Update',
            'hasil_ok' => 'Hasil Ok',
            'hasil_ng' => 'Hasil Ng',
            'total_cek' => 'Total Cek',
        ];
    }




}
