<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.mnt_shift_emp".
 *
 * @property integer $id
 * @property string $nik
 * @property string $name
 * @property string $speed_dial
 * @property string $phone
 * @property integer $flag
 * @property string $aliasModel
 */
abstract class MntShiftEmp extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.mnt_shift_emp';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nik', 'name', 'speed_dial', 'phone'], 'string'],
            [['flag'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nik' => 'Nik',
            'name' => 'Name',
            'speed_dial' => 'Speed Dial',
            'phone' => 'Phone',
            'flag' => 'Flag',
        ];
    }




}
