<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.mnt_shift_sch".
 *
 * @property integer $id
 * @property integer $shift_emp_id
 * @property string $period
 * @property string $shift_date
 * @property string $shift_code
 * @property string $aliasModel
 */
abstract class MntShiftSch extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.mnt_shift_sch';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['shift_emp_id'], 'integer'],
            [['period', 'shift_code'], 'string'],
            [['shift_date'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'shift_emp_id' => 'Shift Emp ID',
            'period' => 'Period',
            'shift_date' => 'Shift Date',
            'shift_code' => 'Shift Code',
        ];
    }




}
