<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.MP_IN_OUT".
 *
 * @property string $MP_ID
 * @property string $NIK
 * @property string $NAMA_KARYAWAN
 * @property string $JENIS_KELAMIN
 * @property string $STATUS_KARYAWAN
 * @property string $DIRECT_INDIRECT
 * @property string $CC_ID
 * @property string $DEPARTEMEN
 * @property string $SECTION
 * @property string $SUB_SECTION
 * @property integer $KONTRAK_KE
 * @property string $PERIOD
 * @property string $TANGGAL
 * @property string $KONTRAK_START
 * @property string $KONTRAK_END
 * @property integer $SKILL
 * @property integer $JUMLAH
 * @property string $TINGKATAN
 * @property string $AKHIR_BULAN
 * @property string $aliasModel
 */
abstract class MpInOut extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.MP_IN_OUT';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['MP_ID'], 'required'],
            [['MP_ID', 'NIK', 'NAMA_KARYAWAN', 'JENIS_KELAMIN', 'STATUS_KARYAWAN', 'DIRECT_INDIRECT', 'CC_ID', 'DEPARTEMEN', 'SECTION', 'SUB_SECTION', 'PERIOD', 'TINGKATAN', 'AKHIR_BULAN'], 'string'],
            [['KONTRAK_KE', 'SKILL', 'JUMLAH'], 'integer'],
            [['TANGGAL', 'KONTRAK_START', 'KONTRAK_END'], 'safe'],
            [['MP_ID'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'MP_ID' => 'Mp  ID',
            'NIK' => 'Nik',
            'NAMA_KARYAWAN' => 'Nama  Karyawan',
            'JENIS_KELAMIN' => 'Jenis  Kelamin',
            'STATUS_KARYAWAN' => 'Status  Karyawan',
            'DIRECT_INDIRECT' => 'Direct  Indirect',
            'CC_ID' => 'Cc  ID',
            'DEPARTEMEN' => 'Departemen',
            'SECTION' => 'Section',
            'SUB_SECTION' => 'Sub  Section',
            'KONTRAK_KE' => 'Kontrak  Ke',
            'PERIOD' => 'Period',
            'TANGGAL' => 'Tanggal',
            'KONTRAK_START' => 'Kontrak  Start',
            'KONTRAK_END' => 'Kontrak  End',
            'SKILL' => 'Skill',
            'JUMLAH' => 'Jumlah',
            'TINGKATAN' => 'Tingkatan',
            'AKHIR_BULAN' => 'Akhir  Bulan',
        ];
    }




}
