<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "mrbs_room".
 *
 * @property integer $id
 * @property integer $disabled
 * @property integer $area_id
 * @property string $room_name
 * @property string $sort_key
 * @property string $description
 * @property integer $capacity
 * @property string $room_admin_email
 * @property string $custom_html
 *
 * @property \app\models\MrbsEntry[] $mrbsEntries
 * @property \app\models\MrbsRepeat[] $mrbsRepeats
 * @property \app\models\MrbsArea $area
 * @property string $aliasModel
 */
abstract class MrbsRoom extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'mrbs_room';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_mrbs');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['disabled', 'area_id', 'capacity'], 'integer'],
            [['room_admin_email', 'custom_html'], 'string'],
            [['room_name', 'sort_key'], 'string', 'max' => 25],
            [['description'], 'string', 'max' => 60],
            [['area_id', 'room_name'], 'unique', 'targetAttribute' => ['area_id', 'room_name']],
            [['area_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\MrbsArea::className(), 'targetAttribute' => ['area_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'disabled' => 'Disabled',
            'area_id' => 'Area ID',
            'room_name' => 'Room Name',
            'sort_key' => 'Sort Key',
            'description' => 'Description',
            'capacity' => 'Capacity',
            'room_admin_email' => 'Room Admin Email',
            'custom_html' => 'Custom Html',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMrbsEntries()
    {
        return $this->hasMany(\app\models\MrbsEntry::className(), ['room_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMrbsRepeats()
    {
        return $this->hasMany(\app\models\MrbsRepeat::className(), ['room_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArea()
    {
        return $this->hasOne(\app\models\MrbsArea::className(), ['id' => 'area_id']);
    }




}
