<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.OFFICE_EMP".
 *
 * @property string $EMP_ID
 * @property string $EMP_NAME
 * @property string $aliasModel
 */
abstract class OfficeEmp extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.OFFICE_EMP';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['EMP_ID'], 'required'],
            [['EMP_NAME'], 'string'],
            [['EMP_ID'], 'string', 'max' => 50],
            [['EMP_ID'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'EMP_ID' => 'Emp ID',
            'EMP_NAME' => 'Emp Name',
        ];
    }




}
