<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "pcb_ng_daily_01".
 *
 * @property integer $period
 * @property string $post_date
 * @property string $total
 * @property string $aliasModel
 */
abstract class PcbNgDaily extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pcb_ng_daily_01';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_redy');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['period', 'total'], 'integer'],
            [['post_date'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'period' => 'Period',
            'post_date' => 'Post Date',
            'total' => 'Total',
        ];
    }




}
