<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "tb_permit_input".
 *
 * @property string $id
 * @property string $nik
 * @property string $nama
 * @property string $dept
 * @property string $atasan
 * @property integer $opsi
 * @property string $tgl
 * @property integer $purpose
 * @property integer $keperluan
 * @property string $card
 * @property integer $status
 * @property integer $update_view
 * @property string $reason
 * @property string $cek_out_plan
 * @property string $cek_in_plan
 * @property string $cek_in_actual
 * @property string $cek_out_actual
 * @property string $handleby
 * @property integer $confirm
 * @property string $aliasModel
 */
abstract class PermitInputData extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tb_permit_input';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_mis7');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'nik', 'nama', 'dept', 'atasan', 'opsi', 'reason', 'cek_out_plan', 'cek_in_plan'], 'required'],
            [['opsi', 'purpose', 'keperluan', 'status', 'update_view', 'confirm'], 'integer'],
            [['tgl', 'cek_out_plan', 'cek_in_plan', 'cek_in_actual', 'cek_out_actual'], 'safe'],
            [['id', 'nik', 'nama', 'dept', 'atasan', 'card', 'reason', 'handleby'], 'string', 'max' => 255],
            [['id'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nik' => 'Nik',
            'nama' => 'Nama',
            'dept' => 'Dept',
            'atasan' => 'Atasan',
            'opsi' => 'Opsi',
            'tgl' => 'Tgl',
            'purpose' => 'Purpose',
            'keperluan' => 'Keperluan',
            'card' => 'Card',
            'status' => 'Status',
            'update_view' => 'Update View',
            'reason' => 'Reason',
            'cek_out_plan' => 'Cek Out Plan',
            'cek_in_plan' => 'Cek In Plan',
            'cek_in_actual' => 'Cek In Actual',
            'cek_out_actual' => 'Cek Out Actual',
            'handleby' => 'Handleby',
            'confirm' => 'Confirm',
        ];
    }




}
