<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;

/**
 * This is the base-model class for table "plan_receiving".
 *
 * @property integer $id
 * @property string $vendor_name
 * @property string $vehicle
 * @property string $item_type
 * @property integer $qty
 * @property string $receiving_date
 * @property string $eta_yemi_date
 * @property string $cut_off_date
 * @property string $etd_port_date
 * @property string $eta_port_date
 * @property string $unloading_time
 * @property string $completed_time
 * @property string $month_periode
 * @property string $container_no
 * @property integer $urgent_status
 * @property string $created_date
 * @property string $last_modified_date
 * @property integer $last_modified_by
 * @property string $deleted_date
 * @property integer $deleted_by
 * @property string $bl_no
 * @property integer $flag
 * @property integer $created_by
 * @property string $aliasModel
 */
abstract class PlanReceiving extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'plan_receiving';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_wh_app');
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'updatedByAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['qty', 'urgent_status', 'last_modified_by', 'deleted_by', 'flag'], 'integer'],
            [['receiving_date'], 'required'],
            [['receiving_date', 'eta_yemi_date', 'cut_off_date', 'etd_port_date', 'eta_port_date', 'unloading_time', 'completed_time', 'created_date', 'last_modified_date', 'deleted_date'], 'safe'],
            [['vendor_name', 'vehicle'], 'string', 'max' => 50],
            [['item_type', 'container_no'], 'string', 'max' => 20],
            [['month_periode'], 'string', 'max' => 7],
            [['bl_no'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'vendor_name' => 'Vendor Name',
            'vehicle' => 'Vehicle',
            'item_type' => 'Item Type',
            'qty' => 'Qty',
            'receiving_date' => 'Receiving Date',
            'eta_yemi_date' => 'Eta Yemi Date',
            'cut_off_date' => 'Cut Off Date',
            'etd_port_date' => 'Etd Port Date',
            'eta_port_date' => 'Eta Port Date',
            'unloading_time' => 'Unloading Time',
            'completed_time' => 'Completed Time',
            'month_periode' => 'Month Periode',
            'container_no' => 'Container No',
            'urgent_status' => 'Urgent Status',
            'created_date' => 'Created Date',
            'created_by' => 'Created By',
            'last_modified_date' => 'Last Modified Date',
            'last_modified_by' => 'Last Modified By',
            'deleted_date' => 'Deleted Date',
            'deleted_by' => 'Deleted By',
            'bl_no' => 'Bl No',
            'flag' => 'Flag',
        ];
    }




}
