<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.PRD_LOSSTIME_TP_ES".
 *
 * @property integer $ID
 * @property string $PERIOD
 * @property string $DESCRIPTION
 * @property integer $QTY
 * @property double $ST_FA
 * @property double $ST_SA
 * @property double $ST_WW
 * @property double $ST_PTG
 * @property double $ST_PCB_MI
 * @property double $ST_SPU
 * @property double $ST_INJ_SMALL
 * @property double $ST_INJ_MEDIUM
 * @property double $ST_INJ_LARGE
 * @property string $aliasModel
 */
abstract class PrdLosstimeTpEs extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.PRD_LOSSTIME_TP_ES';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['DESCRIPTION'], 'string'],
            [['QTY'], 'integer'],
            [['ST_FA', 'ST_SA', 'ST_WW', 'ST_PTG', 'ST_PCB_MI', 'ST_SPU', 'ST_INJ_SMALL', 'ST_INJ_MEDIUM', 'ST_INJ_LARGE'], 'number'],
            [['PERIOD'], 'string', 'max' => 10]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ID' => 'ID',
            'PERIOD' => 'Period',
            'DESCRIPTION' => 'Description',
            'QTY' => 'Qty',
            'ST_FA' => 'St Fa',
            'ST_SA' => 'St Sa',
            'ST_WW' => 'St Ww',
            'ST_PTG' => 'St Ptg',
            'ST_PCB_MI' => 'St Pcb Mi',
            'ST_SPU' => 'St Spu',
            'ST_INJ_SMALL' => 'St Inj Small',
            'ST_INJ_MEDIUM' => 'St Inj Medium',
            'ST_INJ_LARGE' => 'St Inj Large',
        ];
    }




}
