<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "dbo.prod_report".
 *
 * @property integer $id
 * @property string $model_name
 * @property string $prod_date
 * @property integer $prod_qty
 * @property string $aliasModel
 */
abstract class ProdReport extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'dbo.prod_report';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['model_name', 'prod_date'], 'required'],
            [['model_name'], 'string'],
            [['prod_date'], 'safe'],
            [['prod_qty'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'model_name' => 'Model Name',
            'prod_date' => 'Prod Date',
            'prod_qty' => 'Prod Qty',
        ];
    }




}
