<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.PROD_NG_POSITION_VIEW".
 *
 * @property string $ng_loc_id
 * @property string $child_analyst
 * @property integer $ng_category_id
 * @property string $position
 * @property string $category_name
 * @property string $category_detail
 * @property integer $flag
 * @property string $aliasModel
 */
abstract class ProdNgPositionView extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.PROD_NG_POSITION_VIEW';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ng_category_id', 'flag'], 'integer'],
            [['ng_loc_id'], 'string', 'max' => 20],
            [['child_analyst'], 'string', 'max' => 10],
            [['position', 'category_name', 'category_detail'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ng_loc_id' => 'Ng Loc ID',
            'child_analyst' => 'Child Analyst',
            'ng_category_id' => 'Ng Category ID',
            'position' => 'Position',
            'category_name' => 'Category Name',
            'category_detail' => 'Category Detail',
            'flag' => 'Flag',
        ];
    }




}
