<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.PROD_ATTENDANCE_MP_PLAN".
 *
 * @property integer $id
 * @property string $child_analyst
 * @property string $child_analyst_desc
 * @property string $nik
 * @property string $name
 * @property string $from_date
 * @property string $to_date
 * @property string $created_date
 * @property string $created_by_id
 * @property string $last_update
 * @property string $updated_by_id
 * @property integer $flag
 * @property string $aliasModel
 */
abstract class ProdAttendanceMpPlan extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.PROD_ATTENDANCE_MP_PLAN';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['from_date', 'to_date', 'created_date', 'last_update'], 'safe'],
            [['flag'], 'integer'],
            [['child_analyst'], 'string', 'max' => 10],
            [['child_analyst_desc'], 'string', 'max' => 50],
            [['nik', 'created_by_id', 'updated_by_id'], 'string', 'max' => 20],
            [['name'], 'string', 'max' => 250]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'child_analyst' => 'Child Analyst',
            'child_analyst_desc' => 'Child Analyst Desc',
            'nik' => 'Nik',
            'name' => 'Name',
            'from_date' => 'From Date',
            'to_date' => 'To Date',
            'created_date' => 'Created Date',
            'created_by_id' => 'Created By ID',
            'last_update' => 'Last Update',
            'updated_by_id' => 'Updated By ID',
            'flag' => 'Flag',
        ];
    }




}
