<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "inspection".
 *
 * @property string $plan
 * @property string $gmc
 * @property string $description
 * @property string $dst
 * @property integer $week_no
 * @property string $proddate
 * @property string $ship
 * @property string $qa_ok
 * @property string $aliasModel
 */
abstract class ProductionInspection extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'inspection';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_mis7');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['gmc', 'proddate'], 'required'],
            [['dst'], 'string'],
            [['week_no'], 'integer'],
            [['ship'], 'safe'],
            [['plan'], 'string', 'max' => 35],
            [['gmc'], 'string', 'max' => 11],
            [['description'], 'string', 'max' => 63],
            [['proddate'], 'string', 'max' => 10],
            [['qa_ok'], 'string', 'max' => 2]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'plan' => 'Plan',
            'gmc' => 'Gmc',
            'description' => 'Description',
            'dst' => 'Dst',
            'week_no' => 'Week No',
            'proddate' => 'Proddate',
            'ship' => 'Ship',
            'qa_ok' => 'Qa Ok',
        ];
    }




}
