<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.PROD_ATTENDANCE_DATA".
 *
 * @property string $att_data_id
 * @property string $period
 * @property string $posting_date
 * @property string $posting_shift
 * @property string $nik
 * @property string $name
 * @property string $check_in
 * @property string $check_out
 * @property string $child_analyst
 * @property string $child_analyst_desc
 * @property integer $line
 * @property string $machine_id
 * @property string $machine_desc
 * @property string $last_update
 * @property string $current_status
 * @property string $aliasModel
 */
abstract class ProdAttendanceData extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.PROD_ATTENDANCE_DATA';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['att_data_id'], 'required'],
            [['att_data_id', 'period', 'nik', 'name', 'child_analyst', 'child_analyst_desc', 'machine_id', 'machine_desc', 'current_status'], 'string'],
            [['posting_date', 'posting_shift', 'check_in', 'check_out', 'last_update'], 'safe'],
            [['line'], 'integer'],
            [['att_data_id'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'att_data_id' => 'Att Data ID',
            'period' => 'Period',
            'posting_date' => 'Posting Date',
            'posting_shift' => 'Posting Shift',
            'nik' => 'Nik',
            'name' => 'Name',
            'check_in' => 'Check In',
            'check_out' => 'Check Out',
            'child_analyst' => 'Child Analyst',
            'child_analyst_desc' => 'Child Analyst Desc',
            'line' => 'Line',
            'machine_id' => 'Machine ID',
            'machine_desc' => 'Machine Desc',
            'last_update' => 'Last Update',
            'current_status' => 'Current Status',
        ];
    }




}
