<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "prod_daily_progress_01".
 *
 * @property integer $period
 * @property string $plan
 * @property string $qty
 * @property string $act_qty
 * @property string $balance_qty
 * @property string $aliasModel
 */
abstract class ProdDailyProgress01 extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'prod_daily_progress_01';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_mis7');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['period'], 'integer'],
            [['plan'], 'safe'],
            [['qty', 'act_qty', 'balance_qty'], 'number']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'period' => 'Period',
            'plan' => 'Plan',
            'qty' => 'Qty',
            'act_qty' => 'Act Qty',
            'balance_qty' => 'Balance Qty',
        ];
    }




}
