<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.REKAP_ABSENSI_VIEW".
 *
 * @property string $YEAR
 * @property string $PERIOD
 * @property string $NIK
 * @property string $NAMA_KARYAWAN
 * @property string $SECTION
 * @property string $GRADE
 * @property integer $KEHADIRAN
 * @property integer $TOTAL_KARYAWAN
 * @property integer $ALPHA
 * @property integer $IJIN
 * @property integer $SAKIT
 * @property integer $CUTI
 * @property integer $CUTI_KHUSUS
 * @property integer $CUTI_KHUSUS_IJIN
 * @property integer $DISIPLIN
 * @property integer $DATANG_TERLAMBAT
 * @property integer $PULANG_CEPAT
 * @property integer $SHIFT1
 * @property integer $SHIFT2
 * @property integer $SHIFT3
 * @property integer $SHIFT4
 * @property string $aliasModel
 */
abstract class RekapAbsensiView extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.REKAP_ABSENSI_VIEW';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['YEAR', 'PERIOD', 'NIK', 'NAMA_KARYAWAN', 'SECTION', 'GRADE'], 'string'],
            [['KEHADIRAN', 'TOTAL_KARYAWAN', 'ALPHA', 'IJIN', 'SAKIT', 'CUTI', 'CUTI_KHUSUS', 'CUTI_KHUSUS_IJIN', 'DISIPLIN', 'DATANG_TERLAMBAT', 'PULANG_CEPAT', 'SHIFT1', 'SHIFT2', 'SHIFT3', 'SHIFT4'], 'integer'],
            [['DISIPLIN'], 'required']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'YEAR' => 'Year',
            'PERIOD' => 'Period',
            'NIK' => 'Nik',
            'NAMA_KARYAWAN' => 'Nama  Karyawan',
            'SECTION' => 'Section',
            'GRADE' => 'Grade',
            'KEHADIRAN' => 'Kehadiran',
            'TOTAL_KARYAWAN' => 'Total  Karyawan',
            'ALPHA' => 'Alpha',
            'IJIN' => 'Ijin',
            'SAKIT' => 'Sakit',
            'CUTI' => 'Cuti',
            'CUTI_KHUSUS' => 'Cuti  Khusus',
            'CUTI_KHUSUS_IJIN' => 'Cuti  Khusus  Ijin',
            'DISIPLIN' => 'Disiplin',
            'DATANG_TERLAMBAT' => 'Datang  Terlambat',
            'PULANG_CEPAT' => 'Pulang  Cepat',
            'SHIFT1' => 'Shift1',
            'SHIFT2' => 'Shift2',
            'SHIFT3' => 'Shift3',
            'SHIFT4' => 'Shift4',
        ];
    }




}
