<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.SAP_GR_GI_BY_PLANT".
 *
 * @property integer $id
 * @property string $period
 * @property string $category
 * @property string $name_category
 * @property string $valuation_class
 * @property string $name_val
 * @property string $plant
 * @property string $name_plant
 * @property string $currency
 * @property string $material
 * @property string $descriptions
 * @property string $type_price
 * @property double $price
 * @property string $uom
 * @property double $beginning_balance
 * @property double $beginning_balance_amount
 * @property double $receipt
 * @property double $receipt_amount
 * @property double $issue
 * @property double $issue_amount
 * @property double $other
 * @property double $other_amount
 * @property double $std_price_var
 * @property double $ending_balance
 * @property string $ending_balance_amount
 * @property string $nama_file
 * @property string $file_date
 * @property string $aliasModel
 */
abstract class SapGrGiByPlant extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.SAP_GR_GI_BY_PLANT';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['price', 'beginning_balance', 'beginning_balance_amount', 'receipt', 'receipt_amount', 'issue', 'issue_amount', 'other', 'other_amount', 'std_price_var', 'ending_balance'], 'number'],
            [['file_date'], 'safe'],
            [['period', 'category', 'name_category', 'valuation_class', 'name_val', 'plant', 'name_plant', 'currency', 'material', 'descriptions', 'type_price', 'uom', 'ending_balance_amount'], 'string', 'max' => 50],
            [['nama_file'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'period' => 'Period',
            'category' => 'Category',
            'name_category' => 'Name Category',
            'valuation_class' => 'Valuation Class',
            'name_val' => 'Name Val',
            'plant' => 'Plant',
            'name_plant' => 'Name Plant',
            'currency' => 'Currency',
            'material' => 'Material',
            'descriptions' => 'Descriptions',
            'type_price' => 'Type Price',
            'price' => 'Price',
            'uom' => 'Uom',
            'beginning_balance' => 'Beginning Balance',
            'beginning_balance_amount' => 'Beginning Balance Amount',
            'receipt' => 'Receipt',
            'receipt_amount' => 'Receipt Amount',
            'issue' => 'Issue',
            'issue_amount' => 'Issue Amount',
            'other' => 'Other',
            'other_amount' => 'Other Amount',
            'std_price_var' => 'Std Price Var',
            'ending_balance' => 'Ending Balance',
            'ending_balance_amount' => 'Ending Balance Amount',
            'nama_file' => 'Nama File',
            'file_date' => 'File Date',
        ];
    }




}
