<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.SAP_MATERIAL_DOCUMENT_BC".
 *
 * @property string $id
 * @property string $plant
 * @property string $entered_date
 * @property string $entered_datetime
 * @property string $posting_period
 * @property string $posting_date
 * @property string $valcl
 * @property string $movement_type
 * @property string $material
 * @property string $material_description
 * @property double $quantity
 * @property string $unit_of_measure
 * @property string $storage_location
 * @property string $reference
 * @property string $prod_order_no
 * @property string $userid
 * @property string $entered_time
 * @property string $doc_header_text
 * @property double $amount_in_lc
 * @property string $curency
 * @property string $cost_center
 * @property string $mat_doc_line
 * @property string $mat_doc
 * @property string $doc_date
 * @property string $po_line
 * @property string $reservation_no
 * @property string $purchase_order_no
 * @property string $supplier
 * @property string $reason
 * @property string $customer
 * @property string $nama_file
 * @property string $file_date
 * @property string $trans_type
 * @property double $qty_in
 * @property double $qty_out
 * @property string $aliasModel
 */
abstract class SapMaterialDocumentBc extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.SAP_MATERIAL_DOCUMENT_BC';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id'], 'required'],
            [['entered_date', 'entered_datetime', 'posting_date'], 'safe'],
            [['quantity', 'amount_in_lc', 'qty_in', 'qty_out'], 'number'],
            [['id', 'material_description', 'reference', 'prod_order_no', 'userid', 'entered_time', 'doc_header_text', 'cost_center', 'mat_doc', 'doc_date', 'reservation_no', 'purchase_order_no', 'supplier', 'reason', 'customer', 'file_date', 'trans_type'], 'string', 'max' => 50],
            [['plant', 'valcl'], 'string', 'max' => 4],
            [['posting_period'], 'string', 'max' => 6],
            [['movement_type', 'unit_of_measure', 'curency', 'mat_doc_line', 'po_line'], 'string', 'max' => 5],
            [['material', 'storage_location'], 'string', 'max' => 11],
            [['nama_file'], 'string', 'max' => 200],
            [['id'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'plant' => 'Plant',
            'entered_date' => 'Entered Date',
            'entered_datetime' => 'Entered Datetime',
            'posting_period' => 'Posting Period',
            'posting_date' => 'Posting Date',
            'valcl' => 'Valcl',
            'movement_type' => 'Movement Type',
            'material' => 'Material',
            'material_description' => 'Material Description',
            'quantity' => 'Quantity',
            'unit_of_measure' => 'Unit Of Measure',
            'storage_location' => 'Storage Location',
            'reference' => 'Reference',
            'prod_order_no' => 'Prod Order No',
            'userid' => 'Userid',
            'entered_time' => 'Entered Time',
            'doc_header_text' => 'Doc Header Text',
            'amount_in_lc' => 'Amount In Lc',
            'curency' => 'Curency',
            'cost_center' => 'Cost Center',
            'mat_doc_line' => 'Mat Doc Line',
            'mat_doc' => 'Mat Doc',
            'doc_date' => 'Doc Date',
            'po_line' => 'Po Line',
            'reservation_no' => 'Reservation No',
            'purchase_order_no' => 'Purchase Order No',
            'supplier' => 'Supplier',
            'reason' => 'Reason',
            'customer' => 'Customer',
            'nama_file' => 'Nama File',
            'file_date' => 'File Date',
            'trans_type' => 'Trans Type',
            'qty_in' => 'Qty In',
            'qty_out' => 'Qty Out',
        ];
    }




}
