<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.sap_picking_list".
 *
 * @property string $barcode
 * @property string $set_list_no
 * @property string $no
 * @property integer $Id
 * @property string $parent
 * @property string $parent_desc
 * @property string $parent_um
 * @property string $parent_valcl
 * @property string $child
 * @property string $child_desc
 * @property string $child_um
 * @property string $valcl
 * @property string $req_date
 * @property double $plan_qty
 * @property double $qty
 * @property double $req_qty
 * @property string $issue_type
 * @property string $pic
 * @property string $rack_no
 * @property string $loc
 * @property string $analyst
 * @property string $analyst_desc
 * @property string $last_update
 * @property string $user_id
 * @property string $user_desc
 * @property string $status
 * @property string $tahap
 * @property string $add_slip
 * @property string $barcode_label
 * @property double $compl_qty
 * @property double $bo_qty
 * @property string $last_update1
 * @property string $user_id1
 * @property string $user_desc1
 * @property string $add_date
 * @property string $posting_date
 * @property string $storage
 * @property string $pts
 * @property string $PUR_LOC
 * @property string $PUR_LOC_DESC
 * @property string $pic_delivery
 * @property string $division
 * @property string $pts_print
 * @property string $hand
 * @property string $req_date_ori
 * @property string $eta_desc
 * @property string $eta_qty
 * @property string $eta_time
 * @property string $trans_mthd
 * @property string $wh_note
 * @property string $pch_note
 * @property string $stat_ok_ng
 * @property string $user_pts
 * @property string $user_desc_pts
 * @property string $last_update_pts
 * @property string $sap_post_date_sinkron
 * @property string $mrp
 * @property string $dcn_note
 * @property string $wh_valid
 * @property string $release_date
 * @property string $release_user
 * @property string $release_user_desc
 * @property string $VMS_PERIOD
 * @property string $VMS_DATE
 * @property string $hapus
 * @property string $hand_scan
 * @property string $hand_scan_datetime
 * @property string $hand_scan_user
 * @property string $hand_scan_desc
 * @property string $aliasModel
 */
abstract class SapPickingList extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.sap_picking_list';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_wsus');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['barcode'], 'required'],
            [['Id'], 'integer'],
            [['req_date', 'last_update', 'last_update1', 'add_date', 'posting_date', 'req_date_ori', 'last_update_pts', 'release_date', 'VMS_DATE', 'hand_scan_datetime'], 'safe'],
            [['plan_qty', 'qty', 'req_qty', 'compl_qty', 'bo_qty'], 'number'],
            [['barcode', 'division'], 'string', 'max' => 30],
            [['set_list_no', 'parent_desc', 'child_desc', 'analyst_desc', 'user_desc', 'user_desc1', 'PUR_LOC_DESC', 'pic_delivery', 'eta_desc', 'eta_qty', 'eta_time', 'trans_mthd', 'stat_ok_ng', 'user_desc_pts', 'release_user_desc', 'hand_scan_desc'], 'string', 'max' => 50],
            [['no'], 'string', 'max' => 4],
            [['parent', 'parent_valcl', 'child', 'valcl', 'pic', 'rack_no', 'loc'], 'string', 'max' => 15],
            [['parent_um', 'child_um', 'storage'], 'string', 'max' => 5],
            [['issue_type', 'status', 'add_slip', 'pts', 'pts_print', 'hand', 'sap_post_date_sinkron', 'mrp', 'wh_valid', 'hapus', 'hand_scan'], 'string', 'max' => 1],
            [['analyst', 'VMS_PERIOD'], 'string', 'max' => 6],
            [['user_id', 'user_id1', 'user_pts', 'release_user', 'hand_scan_user'], 'string', 'max' => 10],
            [['tahap'], 'string', 'max' => 2],
            [['barcode_label'], 'string', 'max' => 255],
            [['PUR_LOC'], 'string', 'max' => 13],
            [['wh_note'], 'string', 'max' => 100],
            [['pch_note', 'dcn_note'], 'string', 'max' => 200],
            [['barcode'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'barcode' => 'Barcode',
            'set_list_no' => 'Set List No',
            'no' => 'No',
            'Id' => 'ID',
            'parent' => 'Parent',
            'parent_desc' => 'Parent Desc',
            'parent_um' => 'Parent Um',
            'parent_valcl' => 'Parent Valcl',
            'child' => 'Child',
            'child_desc' => 'Child Desc',
            'child_um' => 'Child Um',
            'valcl' => 'Valcl',
            'req_date' => 'Req Date',
            'plan_qty' => 'Plan Qty',
            'qty' => 'Qty',
            'req_qty' => 'Req Qty',
            'issue_type' => 'Issue Type',
            'pic' => 'Pic',
            'rack_no' => 'Rack No',
            'loc' => 'Loc',
            'analyst' => 'Analyst',
            'analyst_desc' => 'Analyst Desc',
            'last_update' => 'Last Update',
            'user_id' => 'User ID',
            'user_desc' => 'User Desc',
            'status' => 'Status',
            'tahap' => 'Tahap',
            'add_slip' => 'Add Slip',
            'barcode_label' => 'Barcode Label',
            'compl_qty' => 'Compl Qty',
            'bo_qty' => 'Bo Qty',
            'last_update1' => 'Last Update1',
            'user_id1' => 'User Id1',
            'user_desc1' => 'User Desc1',
            'add_date' => 'Add Date',
            'posting_date' => 'Posting Date',
            'storage' => 'Storage',
            'pts' => 'Pts',
            'PUR_LOC' => 'Pur Loc',
            'PUR_LOC_DESC' => 'Pur Loc Desc',
            'pic_delivery' => 'Pic Delivery',
            'division' => 'Division',
            'pts_print' => 'Pts Print',
            'hand' => 'Hand',
            'req_date_ori' => 'Req Date Ori',
            'eta_desc' => 'Eta Desc',
            'eta_qty' => 'Eta Qty',
            'eta_time' => 'Eta Time',
            'trans_mthd' => 'Trans Mthd',
            'wh_note' => 'Wh Note',
            'pch_note' => 'Pch Note',
            'stat_ok_ng' => 'Stat Ok Ng',
            'user_pts' => 'User Pts',
            'user_desc_pts' => 'User Desc Pts',
            'last_update_pts' => 'Last Update Pts',
            'sap_post_date_sinkron' => 'Sap Post Date Sinkron',
            'mrp' => 'Mrp',
            'dcn_note' => 'Dcn Note',
            'wh_valid' => 'Wh Valid',
            'release_date' => 'Release Date',
            'release_user' => 'Release User',
            'release_user_desc' => 'Release User Desc',
            'VMS_PERIOD' => 'Vms Period',
            'VMS_DATE' => 'Vms Date',
            'hapus' => 'Hapus',
            'hand_scan' => 'Hand Scan',
            'hand_scan_datetime' => 'Hand Scan Datetime',
            'hand_scan_user' => 'Hand Scan User',
            'hand_scan_desc' => 'Hand Scan Desc',
        ];
    }




}
