<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.sap_po_rcv".
 *
 * @property integer $seq_id
 * @property string $local_import
 * @property string $currency
 * @property double $rate
 * @property string $abc_indicator
 * @property string $vendor_code
 * @property string $vendor_name
 * @property string $payment_terms
 * @property string $freight_cond_type
 * @property double $freight
 * @property string $insurance_cond_type
 * @property double $insurance
 * @property string $internal_exp_cond_type
 * @property double $internal_exp
 * @property string $no
 * @property string $rcv_date
 * @property string $material_document_number
 * @property string $item_no
 * @property string $inv_no
 * @property string $po_id
 * @property string $slip_no
 * @property string $acct_assig_cat
 * @property string $material
 * @property string $description
 * @property double $quantity
 * @property string $um
 * @property double $quantity_pur_unit
 * @property string $pur_um
 * @property double $unit_price
 * @property double $amount_rcv
 * @property double $amount_ppn
 * @property double $amount_wh
 * @property double $amount_usd
 * @property double $amount_freight
 * @property double $amount_insurance
 * @property double $amount_internal_exp
 * @property double $amount_total_charges
 * @property double $amount_total
 * @property string $direct_indirect
 * @property double $std_price
 * @property double $std_amount
 * @property string $nat_acc
 * @property string $nat_acc_desc
 * @property string $cost_center
 * @property string $cost_center_desc
 * @property string $purchasing_group
 * @property string $vendor_country_code
 * @property string $order_date
 * @property double $order_quantity
 * @property string $order_delivery_date
 * @property string $relied_delivery_date
 * @property double $relied_delivery_qty
 * @property string $storage_location_po
 * @property string $movement_type
 * @property string $lt_po
 * @property string $grt_po
 * @property string $stock_type_po
 * @property string $delivery_completed
 * @property string $cust_doc_date
 * @property string $doc_type
 * @property string $cust_doc_no
 * @property string $po_no
 * @property string $po_line
 * @property string $upload
 * @property string $period
 * @property string $fix_add
 * @property string $voucher_no
 * @property string $invoice_act
 * @property string $kwitansi_act
 * @property double $price_act
 * @property double $amount_act
 * @property double $variance_act
 * @property string $status
 * @property string $bc_type
 * @property string $bc_no
 * @property string $bc_date
 * @property string $sign
 * @property string $upload_date
 * @property string $asano_doc
 * @property string $asano_invoice
 * @property string $pic
 * @property string $division
 * @property string $sinkron
 * @property string $Inspection_level
 * @property string $Judgement
 * @property string $Remark
 * @property string $aliasModel
 */
abstract class SapPoRcv extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.sap_po_rcv';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_wsus');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['local_import', 'currency', 'abc_indicator', 'vendor_code', 'vendor_name', 'payment_terms', 'freight_cond_type', 'insurance_cond_type', 'internal_exp_cond_type', 'no', 'material_document_number', 'item_no', 'inv_no', 'po_id', 'slip_no', 'acct_assig_cat', 'material', 'description', 'um', 'pur_um', 'direct_indirect', 'nat_acc', 'nat_acc_desc', 'cost_center', 'cost_center_desc', 'purchasing_group', 'vendor_country_code', 'storage_location_po', 'movement_type', 'lt_po', 'grt_po', 'stock_type_po', 'delivery_completed', 'cust_doc_date', 'doc_type', 'cust_doc_no', 'po_no', 'po_line', 'upload', 'period', 'fix_add', 'voucher_no', 'invoice_act', 'kwitansi_act', 'status', 'bc_type', 'bc_no', 'sign', 'asano_doc', 'asano_invoice', 'pic', 'division', 'sinkron', 'Inspection_level', 'Judgement', 'Remark'], 'string'],
            [['rate', 'freight', 'insurance', 'internal_exp', 'quantity', 'quantity_pur_unit', 'unit_price', 'amount_rcv', 'amount_ppn', 'amount_wh', 'amount_usd', 'amount_freight', 'amount_insurance', 'amount_internal_exp', 'amount_total_charges', 'amount_total', 'std_price', 'std_amount', 'order_quantity', 'relied_delivery_qty', 'price_act', 'amount_act', 'variance_act'], 'number'],
            [['rcv_date', 'order_date', 'order_delivery_date', 'relied_delivery_date', 'bc_date', 'upload_date'], 'safe'],
            [['material_document_number'], 'required'],
            [['material_document_number'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'seq_id' => 'Seq ID',
            'local_import' => 'Local Import',
            'currency' => 'Currency',
            'rate' => 'Rate',
            'abc_indicator' => 'Abc Indicator',
            'vendor_code' => 'Vendor Code',
            'vendor_name' => 'Vendor Name',
            'payment_terms' => 'Payment Terms',
            'freight_cond_type' => 'Freight Cond Type',
            'freight' => 'Freight',
            'insurance_cond_type' => 'Insurance Cond Type',
            'insurance' => 'Insurance',
            'internal_exp_cond_type' => 'Internal Exp Cond Type',
            'internal_exp' => 'Internal Exp',
            'no' => 'No',
            'rcv_date' => 'Rcv Date',
            'material_document_number' => 'Material Document Number',
            'item_no' => 'Item No',
            'inv_no' => 'Inv No',
            'po_id' => 'Po ID',
            'slip_no' => 'Slip No',
            'acct_assig_cat' => 'Acct Assig Cat',
            'material' => 'Material',
            'description' => 'Description',
            'quantity' => 'Quantity',
            'um' => 'Um',
            'quantity_pur_unit' => 'Quantity Pur Unit',
            'pur_um' => 'Pur Um',
            'unit_price' => 'Unit Price',
            'amount_rcv' => 'Amount Rcv',
            'amount_ppn' => 'Amount Ppn',
            'amount_wh' => 'Amount Wh',
            'amount_usd' => 'Amount Usd',
            'amount_freight' => 'Amount Freight',
            'amount_insurance' => 'Amount Insurance',
            'amount_internal_exp' => 'Amount Internal Exp',
            'amount_total_charges' => 'Amount Total Charges',
            'amount_total' => 'Amount Total',
            'direct_indirect' => 'Direct Indirect',
            'std_price' => 'Std Price',
            'std_amount' => 'Std Amount',
            'nat_acc' => 'Nat Acc',
            'nat_acc_desc' => 'Nat Acc Desc',
            'cost_center' => 'Cost Center',
            'cost_center_desc' => 'Cost Center Desc',
            'purchasing_group' => 'Purchasing Group',
            'vendor_country_code' => 'Vendor Country Code',
            'order_date' => 'Order Date',
            'order_quantity' => 'Order Quantity',
            'order_delivery_date' => 'Order Delivery Date',
            'relied_delivery_date' => 'Relied Delivery Date',
            'relied_delivery_qty' => 'Relied Delivery Qty',
            'storage_location_po' => 'Storage Location Po',
            'movement_type' => 'Movement Type',
            'lt_po' => 'Lt Po',
            'grt_po' => 'Grt Po',
            'stock_type_po' => 'Stock Type Po',
            'delivery_completed' => 'Delivery Completed',
            'cust_doc_date' => 'Cust Doc Date',
            'doc_type' => 'Doc Type',
            'cust_doc_no' => 'Cust Doc No',
            'po_no' => 'Po No',
            'po_line' => 'Po Line',
            'upload' => 'Upload',
            'period' => 'Period',
            'fix_add' => 'Fix Add',
            'voucher_no' => 'Voucher No',
            'invoice_act' => 'Invoice Act',
            'kwitansi_act' => 'Kwitansi Act',
            'price_act' => 'Price Act',
            'amount_act' => 'Amount Act',
            'variance_act' => 'Variance Act',
            'status' => 'Status',
            'bc_type' => 'Bc Type',
            'bc_no' => 'Bc No',
            'bc_date' => 'Bc Date',
            'sign' => 'Sign',
            'upload_date' => 'Upload Date',
            'asano_doc' => 'Asano Doc',
            'asano_invoice' => 'Asano Invoice',
            'pic' => 'Pic',
            'division' => 'Division',
            'sinkron' => 'Sinkron',
            'Inspection_level' => 'Inspection Level',
            'Judgement' => 'Judgement',
            'Remark' => 'Remark',
        ];
    }




}
