<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.sap_picking_pts_old_cur".
 *
 * @property string $barcode
 * @property string $period
 * @property string $req_date
 * @property string $child
 * @property string $child_desc
 * @property string $child_um
 * @property double $req_qty
 * @property double $compl_qty
 * @property double $bo_qty
 * @property string $posting_date
 * @property string $pts
 * @property string $PUR_LOC
 * @property string $PUR_LOC_DESC
 * @property string $pic_delivery
 * @property string $division
 * @property string $STATUS
 * @property integer $COUNT
 * @property string $aliasModel
 */
abstract class SapPickingPtsDetailView extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.sap_picking_pts_old_cur';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_wsus');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['barcode', 'compl_qty', 'COUNT'], 'required'],
            [['barcode', 'period', 'child', 'child_desc', 'child_um', 'pts', 'PUR_LOC', 'PUR_LOC_DESC', 'pic_delivery', 'division', 'STATUS'], 'string'],
            [['req_date', 'posting_date'], 'safe'],
            [['req_qty', 'compl_qty', 'bo_qty'], 'number'],
            [['COUNT'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'barcode' => 'Barcode',
            'period' => 'Period',
            'req_date' => 'Req Date',
            'child' => 'Child',
            'child_desc' => 'Child Desc',
            'child_um' => 'Child Um',
            'req_qty' => 'Req Qty',
            'compl_qty' => 'Compl Qty',
            'bo_qty' => 'Bo Qty',
            'posting_date' => 'Posting Date',
            'pts' => 'Pts',
            'PUR_LOC' => 'Pur  Loc',
            'PUR_LOC_DESC' => 'Pur  Loc  Desc',
            'pic_delivery' => 'Pic Delivery',
            'division' => 'Division',
            'STATUS' => 'Status',
            'COUNT' => 'Count',
        ];
    }




}
