<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.SENSOR_LOG".
 *
 * @property integer $seq
 * @property string $loc_no
 * @property string $Factory
 * @property string $location
 * @property string $area
 * @property double $temparature
 * @property double $humidity
 * @property string $system_date_time
 * @property double $map_no
 * @property string $aliasModel
 */
abstract class SensorLog extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.SENSOR_LOG';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['loc_no', 'Factory', 'location', 'area'], 'string'],
            [['temparature', 'humidity', 'map_no'], 'number'],
            [['system_date_time'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'seq' => 'Seq',
            'loc_no' => 'Loc No',
            'Factory' => 'Factory',
            'location' => 'Location',
            'area' => 'Area',
            'temparature' => 'Temparature',
            'humidity' => 'Humidity',
            'system_date_time' => 'System Date Time',
            'map_no' => 'Map No',
        ];
    }




}
