<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "tb_serno_calendar".
 *
 * @property string $ship
 * @property integer $week_ship
 * @property string $etd
 * @property string $aliasModel
 */
abstract class SernoCalendar extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tb_serno_calendar';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_mis7');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ship', 'week_ship', 'etd'], 'required'],
            [['ship', 'etd'], 'safe'],
            [['week_ship'], 'integer'],
            [['ship'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ship' => 'Ship',
            'week_ship' => 'Week Ship',
            'etd' => 'Etd',
        ];
    }




}
