<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "tb_serno_input_plan".
 *
 * @property string $pk
 * @property integer $nik
 * @property string $line
 * @property string $gmc
 * @property string $plan
 * @property integer $qty
 * @property integer $act_qty
 * @property integer $balance_qty
 * @property string $last_update_output
 * @property string $aliasModel
 */
abstract class SernoInputPlan extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tb_serno_input_plan';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_mis7');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['pk', 'nik', 'line', 'gmc', 'plan', 'qty'], 'required'],
            [['nik', 'qty', 'act_qty', 'balance_qty'], 'integer'],
            [['plan', 'last_update_output'], 'safe'],
            [['pk', 'line', 'gmc'], 'string', 'max' => 255],
            [['pk'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'pk' => 'Pk',
            'nik' => 'Nik',
            'line' => 'Line',
            'gmc' => 'Gmc',
            'plan' => 'Plan',
            'qty' => 'Qty',
            'act_qty' => 'Act Qty',
            'balance_qty' => 'Balance Qty',
            'last_update_output' => 'Last Update Output',
        ];
    }




}
