<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "tb_serno_slip".
 *
 * @property string $user
 * @property string $id
 * @property integer $slip
 * @property integer $fa
 * @property integer $status
 * @property integer $status2
 * @property string $aliasModel
 */
abstract class SernoSlip extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tb_serno_slip';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_mis7');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user', 'id', 'slip'], 'required'],
            [['slip', 'fa', 'status', 'status2'], 'integer'],
            [['user'], 'string', 'max' => 10],
            [['id'], 'string', 'max' => 2],
            [['user'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'user' => 'User',
            'id' => 'ID',
            'slip' => 'Slip',
            'fa' => 'Fa',
            'status' => 'Status',
            'status2' => 'Status2',
        ];
    }




}
