<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "tb_serno_master".
 *
 * @property string $gmc
 * @property string $model
 * @property string $color
 * @property string $dest
 * @property string $package
 * @property integer $package_qty
 * @property integer $pallet
 * @property string $line
 * @property double $st
 * @property double $eff
 * @property integer $safety
 * @property string $id_log
 * @property string $log_date
 * @property string $hpl_desc
 * @property string $bu
 * @property string $fg_kd
 * @property integer $eff_target
 * @property string $aliasModel
 */
abstract class SernoMaster extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tb_serno_master';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_mis7');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['gmc', 'eff_target'], 'required'],
            [['package_qty', 'pallet', 'safety', 'eff_target'], 'integer'],
            [['st', 'eff'], 'number'],
            [['gmc', 'model', 'color', 'dest', 'package', 'line', 'id_log', 'log_date', 'hpl_desc'], 'string', 'max' => 255],
            [['bu', 'fg_kd'], 'string', 'max' => 20],
            [['gmc'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'gmc' => 'Gmc',
            'model' => 'Model',
            'color' => 'Color',
            'dest' => 'Dest',
            'package' => 'Package',
            'package_qty' => 'Package Qty',
            'pallet' => 'Pallet',
            'line' => 'Line',
            'st' => 'St',
            'eff' => 'Eff',
            'safety' => 'Safety',
            'id_log' => 'Id Log',
            'log_date' => 'Log Date',
            'hpl_desc' => 'Hpl Desc',
            'bu' => 'Bu',
            'fg_kd' => 'Fg Kd',
            'eff_target' => 'Eff Target',
        ];
    }




}
