<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "tb_serno_slip_log2".
 *
 * @property string $pk
 * @property string $line
 * @property string $start
 * @property string $end
 * @property string $arrival_time
 * @property string $nik
 * @property string $departure_datetime
 * @property string $arrival_datetime
 * @property integer $completion_time
 * @property string $aliasModel
 */
abstract class SernoSlipLog2 extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tb_serno_slip_log2';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_mis7');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['pk'], 'required'],
            [['pk', 'start', 'end', 'arrival_time', 'departure_datetime', 'arrival_datetime'], 'safe'],
            [['completion_time'], 'integer'],
            [['line', 'nik'], 'string', 'max' => 255],
            [['pk'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'pk' => 'Pk',
            'line' => 'Line',
            'start' => 'Start',
            'end' => 'End',
            'arrival_time' => 'Arrival Time',
            'nik' => 'Nik',
            'departure_datetime' => 'Departure Datetime',
            'arrival_datetime' => 'Arrival Datetime',
            'completion_time' => 'Completion Time',
        ];
    }




}
