<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "tb_serno_output".
 *
 * @property string $pk_plan
 * @property string $uniq_plan
 * @property integer $num_plan
 * @property string $stc_plan
 * @property string $gmc_plan
 * @property integer $qty_plan
 * @property string $prod_plan
 * @property string $ship_plan
 * @property integer $prod_week_plan
 * @property integer $ship_week_plan
 * @property string $mdsi_plan
 * @property integer $prod_output_plan
 * @property integer $ship_output_plan
 * @property string $aliasModel
 */
abstract class SernoOutput extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tb_serno_output';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['pk_plan', 'prod_output_plan', 'ship_output_plan'], 'required'],
            [['num_plan', 'qty_plan', 'prod_week_plan', 'ship_week_plan', 'prod_output_plan', 'ship_output_plan'], 'integer'],
            [['pk_plan', 'prod_plan', 'ship_plan'], 'string', 'max' => 10],
            [['uniq_plan', 'stc_plan'], 'string', 'max' => 6],
            [['gmc_plan'], 'string', 'max' => 7],
            [['mdsi_plan'], 'string', 'max' => 9]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'pk_plan' => 'Pk Plan',
            'uniq_plan' => 'Uniq Plan',
            'num_plan' => 'Num Plan',
            'stc_plan' => 'Stc Plan',
            'gmc_plan' => 'Gmc Plan',
            'qty_plan' => 'Qty Plan',
            'prod_plan' => 'Prod Plan',
            'ship_plan' => 'Ship Plan',
            'prod_week_plan' => 'Prod Week Plan',
            'ship_week_plan' => 'Ship Week Plan',
            'mdsi_plan' => 'Mdsi Plan',
            'prod_output_plan' => 'Prod Output Plan',
            'ship_output_plan' => 'Ship Output Plan',
        ];
    }




}
