<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "tb_serno_input_all".
 *
 * @property string $pk
 * @property string $gmc
 * @property string $line
 * @property double $mp
 * @property string $proddate
 * @property string $waktu
 * @property double $wrk_time
 * @property double $mp_time
 * @property double $qty_time
 * @property string $sernum
 * @property integer $flo
 * @property string $plan
 * @property integer $adv
 * @property string $qa_ok
 * @property string $qa_ok_date
 * @property string $qa_ng
 * @property string $qa_ng_date
 * @property integer $qa_result
 * @property integer $loct
 * @property string $loct_time
 * @property integer $reprint
 * @property string $aliasModel
 */
abstract class SernoInputAll extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tb_serno_input_all';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_mis7');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['mp', 'wrk_time', 'mp_time', 'qty_time'], 'number'],
            [['waktu', 'loct_time'], 'safe'],
            [['flo', 'adv', 'qa_result', 'loct', 'reprint'], 'integer'],
            [['pk'], 'string', 'max' => 40],
            [['gmc'], 'string', 'max' => 11],
            [['line'], 'string', 'max' => 15],
            [['proddate'], 'string', 'max' => 10],
            [['sernum'], 'string', 'max' => 20],
            [['plan'], 'string', 'max' => 35],
            [['qa_ok'], 'string', 'max' => 2],
            [['qa_ok_date', 'qa_ng', 'qa_ng_date'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'pk' => 'Pk',
            'gmc' => 'Gmc',
            'line' => 'Line',
            'mp' => 'Mp',
            'proddate' => 'Proddate',
            'waktu' => 'Waktu',
            'wrk_time' => 'Wrk Time',
            'mp_time' => 'Mp Time',
            'qty_time' => 'Qty Time',
            'sernum' => 'Sernum',
            'flo' => 'Flo',
            'plan' => 'Plan',
            'adv' => 'Adv',
            'qa_ok' => 'Qa Ok',
            'qa_ok_date' => 'Qa Ok Date',
            'qa_ng' => 'Qa Ng',
            'qa_ng_date' => 'Qa Ng Date',
            'qa_result' => 'Qa Result',
            'loct' => 'Loct',
            'loct_time' => 'Loct Time',
            'reprint' => 'Reprint',
        ];
    }




}
