<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.SERVER_BACK_UP_CUR".
 *
 * @property string $database_name
 * @property string $back_up_period
 * @property string $file_name
 * @property double $size_Gb
 * @property string $last_backup
 * @property string $last_update
 * @property string $aliasModel
 */
abstract class ServerBackupCurrent extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.SERVER_BACK_UP_CUR';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['database_name'], 'required'],
            [['size_Gb'], 'number'],
            [['last_backup', 'last_update'], 'safe'],
            [['database_name'], 'string', 'max' => 50],
            [['back_up_period', 'file_name'], 'string', 'max' => 200],
            [['database_name'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'database_name' => 'Database Name',
            'back_up_period' => 'Back Up Period',
            'file_name' => 'File Name',
            'size_Gb' => 'Size Gb',
            'last_backup' => 'Last Backup',
            'last_update' => 'Last Update',
        ];
    }




}
