<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.SHIFT_PATROL_CATEGORY_TBL".
 *
 * @property integer $id
 * @property integer $order_num
 * @property string $category_desc
 * @property integer $flag
 * @property string $aliasModel
 */
abstract class ShiftPatrolCategoryTbl extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.SHIFT_PATROL_CATEGORY_TBL';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['order_num', 'flag'], 'integer'],
            [['category_desc'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'order_num' => 'Order Num',
            'category_desc' => 'Category Desc',
            'flag' => 'Flag',
        ];
    }




}
