<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.SHIFT_PATROL_REJECT_HISTORY".
 *
 * @property integer $id
 * @property integer $reference_id
 * @property string $rejector_id
 * @property string $rejector_name
 * @property string $reject_remark
 * @property string $reject_datetime
 * @property string $answerer_id
 * @property string $answerer_name
 * @property string $answerer_remark
 * @property string $answerer_datetime
 * @property string $aliasModel
 */
abstract class ShiftPatrolRejectHistory extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.SHIFT_PATROL_REJECT_HISTORY';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['reference_id'], 'integer'],
            [['rejector_id', 'rejector_name', 'reject_remark', 'answerer_id', 'answerer_name', 'answerer_remark'], 'string'],
            [['reject_datetime', 'answerer_datetime'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'reference_id' => 'Reference ID',
            'rejector_id' => 'Rejector ID',
            'rejector_name' => 'Rejector Name',
            'reject_remark' => 'Reject Remark',
            'reject_datetime' => 'Reject Datetime',
            'answerer_id' => 'Answerer ID',
            'answerer_name' => 'Answerer Name',
            'answerer_remark' => 'Answerer Remark',
            'answerer_datetime' => 'Answerer Datetime',
        ];
    }




}
