<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.SHIP_PRD_MONTHLY_RESULT".
 *
 * @property string $PERIOD
 * @property double $SHIP_PLAN_ORI_QTY
 * @property double $SHIP_PLAN_ORI_AMT
 * @property double $SHIP_PLAN_BO_QTY
 * @property double $SHIP_PLAN_BO_AMT
 * @property double $SHIP_PLAN_TOTAL_QTY
 * @property double $SHIP_PLAN_TOTAL_AMT
 * @property double $SHIP_ACT_ORI_QTY
 * @property double $SHIP_ACT_ORI_AMT
 * @property double $SHIP_ACT_BO_QTY
 * @property double $SHIP_ACT_BO_AMT
 * @property double $SHIP_ACT_TOTAL_QTY
 * @property double $SHIP_ACT_TOTAL_AMT
 * @property double $PRD_PLAN_ORI_QTY
 * @property double $PRD_PLAN_ORI_AMT
 * @property double $PRD_PLAN_DELAY_QTY
 * @property double $PRD_PLAN_DELAY_AMT
 * @property double $PRD_PLAN_TOTAL_QTY
 * @property double $PRD_PLAN_TOTAL_AMT
 * @property double $PRD_ACT_ORI_QTY
 * @property double $PRD_ACT_ORI_AMT
 * @property double $PRD_ACT_DELAY_QTY
 * @property double $PRD_ACT_DELAY_AMT
 * @property double $PRD_ACT_TOTAL_QTY
 * @property double $PRD_ACT_TOTAL_AMT
 * @property string $aliasModel
 */
abstract class ShipPrdMonthlyResult extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.SHIP_PRD_MONTHLY_RESULT';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['PERIOD'], 'required'],
            [['SHIP_PLAN_ORI_QTY', 'SHIP_PLAN_ORI_AMT', 'SHIP_PLAN_BO_QTY', 'SHIP_PLAN_BO_AMT', 'SHIP_PLAN_TOTAL_QTY', 'SHIP_PLAN_TOTAL_AMT', 'SHIP_ACT_ORI_QTY', 'SHIP_ACT_ORI_AMT', 'SHIP_ACT_BO_QTY', 'SHIP_ACT_BO_AMT', 'SHIP_ACT_TOTAL_QTY', 'SHIP_ACT_TOTAL_AMT', 'PRD_PLAN_ORI_QTY', 'PRD_PLAN_ORI_AMT', 'PRD_PLAN_DELAY_QTY', 'PRD_PLAN_DELAY_AMT', 'PRD_PLAN_TOTAL_QTY', 'PRD_PLAN_TOTAL_AMT', 'PRD_ACT_ORI_QTY', 'PRD_ACT_ORI_AMT', 'PRD_ACT_DELAY_QTY', 'PRD_ACT_DELAY_AMT', 'PRD_ACT_TOTAL_QTY', 'PRD_ACT_TOTAL_AMT'], 'number'],
            [['PERIOD'], 'string', 'max' => 10],
            [['PERIOD'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'PERIOD' => 'Period',
            'SHIP_PLAN_ORI_QTY' => 'Ship Plan Ori Qty',
            'SHIP_PLAN_ORI_AMT' => 'Ship Plan Ori Amt',
            'SHIP_PLAN_BO_QTY' => 'Ship Plan Bo Qty',
            'SHIP_PLAN_BO_AMT' => 'Ship Plan Bo Amt',
            'SHIP_PLAN_TOTAL_QTY' => 'Ship Plan Total Qty',
            'SHIP_PLAN_TOTAL_AMT' => 'Ship Plan Total Amt',
            'SHIP_ACT_ORI_QTY' => 'Ship Act Ori Qty',
            'SHIP_ACT_ORI_AMT' => 'Ship Act Ori Amt',
            'SHIP_ACT_BO_QTY' => 'Ship Act Bo Qty',
            'SHIP_ACT_BO_AMT' => 'Ship Act Bo Amt',
            'SHIP_ACT_TOTAL_QTY' => 'Ship Act Total Qty',
            'SHIP_ACT_TOTAL_AMT' => 'Ship Act Total Amt',
            'PRD_PLAN_ORI_QTY' => 'Prd Plan Ori Qty',
            'PRD_PLAN_ORI_AMT' => 'Prd Plan Ori Amt',
            'PRD_PLAN_DELAY_QTY' => 'Prd Plan Delay Qty',
            'PRD_PLAN_DELAY_AMT' => 'Prd Plan Delay Amt',
            'PRD_PLAN_TOTAL_QTY' => 'Prd Plan Total Qty',
            'PRD_PLAN_TOTAL_AMT' => 'Prd Plan Total Amt',
            'PRD_ACT_ORI_QTY' => 'Prd Act Ori Qty',
            'PRD_ACT_ORI_AMT' => 'Prd Act Ori Amt',
            'PRD_ACT_DELAY_QTY' => 'Prd Act Delay Qty',
            'PRD_ACT_DELAY_AMT' => 'Prd Act Delay Amt',
            'PRD_ACT_TOTAL_QTY' => 'Prd Act Total Qty',
            'PRD_ACT_TOTAL_AMT' => 'Prd Act Total Amt',
        ];
    }




}
