<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.SHIP_ITEM_M3".
 *
 * @property string $ITEM
 * @property string $ITEM_DESC
 * @property string $UM
 * @property string $EAN_UPC
 * @property string $CT
 * @property double $LENGTH
 * @property double $WIDTH
 * @property double $HEIGHT
 * @property string $UNIT
 * @property double $VOLUME
 * @property string $VUN
 * @property double $GROSS
 * @property string $WUN
 * @property string $aliasModel
 */
abstract class ShipItemM3 extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.SHIP_ITEM_M3';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ITEM'], 'required'],
            [['ITEM', 'ITEM_DESC', 'UM', 'EAN_UPC', 'CT', 'UNIT', 'VUN', 'WUN'], 'string'],
            [['LENGTH', 'WIDTH', 'HEIGHT', 'VOLUME', 'GROSS'], 'number'],
            [['ITEM'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ITEM' => 'Item',
            'ITEM_DESC' => 'Item  Desc',
            'UM' => 'Um',
            'EAN_UPC' => 'Ean  Upc',
            'CT' => 'Ct',
            'LENGTH' => 'Length',
            'WIDTH' => 'Width',
            'HEIGHT' => 'Height',
            'UNIT' => 'Unit',
            'VOLUME' => 'Volume',
            'VUN' => 'Vun',
            'GROSS' => 'Gross',
            'WUN' => 'Wun',
        ];
    }




}
