<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "tb_ship_customer".
 *
 * @property integer $id
 * @property string $customer_code
 * @property string $customer_desc
 * @property string $port_name
 * @property string $country_name
 * @property string $aliasModel
 */
abstract class ShipCustomer extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tb_ship_customer';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_mis7');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['customer_code'], 'string', 'max' => 10],
            [['customer_desc'], 'string', 'max' => 100],
            [['port_name', 'country_name'], 'string', 'max' => 20]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'customer_code' => 'Customer Code',
            'customer_desc' => 'Customer Desc',
            'port_name' => 'Port Name',
            'country_name' => 'Country Name',
        ];
    }




}
