<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.SHIPPING_ORDER_VIEW_01".
 *
 * @property string $HDR_ID
 * @property string $YCJ_REF_NO
 * @property string $PERIOD
 * @property string $POD
 * @property integer $CONFIRM_40HC
 * @property integer $CONFIRM_40
 * @property integer $CONFIRM_20
 * @property integer $CONFIRM_LCL
 * @property integer $UNCONFIRM_40HC
 * @property integer $UNCONFIRM_40
 * @property integer $UNCONFIRM_20
 * @property integer $UNCONFIRM_LCL
 * @property string $STATUS_CONFIRMED
 * @property string $aliasModel
 */
abstract class ShippingOrderView01 extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.SHIPPING_ORDER_VIEW_01';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['HDR_ID', 'YCJ_REF_NO', 'CONFIRM_40HC', 'CONFIRM_40', 'CONFIRM_20', 'CONFIRM_LCL', 'STATUS_CONFIRMED'], 'required'],
            [['CONFIRM_40HC', 'CONFIRM_40', 'CONFIRM_20', 'CONFIRM_LCL', 'UNCONFIRM_40HC', 'UNCONFIRM_40', 'UNCONFIRM_20', 'UNCONFIRM_LCL'], 'integer'],
            [['HDR_ID', 'POD'], 'string', 'max' => 50],
            [['YCJ_REF_NO'], 'string', 'max' => 20],
            [['PERIOD'], 'string', 'max' => 10],
            [['STATUS_CONFIRMED'], 'string', 'max' => 11]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'HDR_ID' => 'Hdr ID',
            'YCJ_REF_NO' => 'Ycj Ref No',
            'PERIOD' => 'Period',
            'POD' => 'Pod',
            'CONFIRM_40HC' => 'Confirm 40 Hc',
            'CONFIRM_40' => 'Confirm 40',
            'CONFIRM_20' => 'Confirm 20',
            'CONFIRM_LCL' => 'Confirm Lcl',
            'UNCONFIRM_40HC' => 'Unconfirm 40 Hc',
            'UNCONFIRM_40' => 'Unconfirm 40',
            'UNCONFIRM_20' => 'Unconfirm 20',
            'UNCONFIRM_LCL' => 'Unconfirm Lcl',
            'STATUS_CONFIRMED' => 'Status Confirmed',
        ];
    }




}
