<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.SHIP_RESERVATION_DTR".
 *
 * @property string $DTR_ID
 * @property string $HDR_ID
 * @property string $YCJ_REF_NO
 * @property string $RESERVATION_NO
 * @property string $DO_NO
 * @property string $BL_NO
 * @property string $HELP
 * @property string $STATUS
 * @property string $SHIPPER
 * @property string $POL
 * @property string $POD
 * @property integer $CNT_40HC
 * @property integer $CNT_40
 * @property integer $CNT_20
 * @property integer $LCL
 * @property string $CARRIER
 * @property integer $FLAG_PRIORITY
 * @property string $FLAG_DESC
 * @property string $ETD
 * @property string $ETD_SUB
 * @property string $KD_FLAG
 * @property string $PERIOD
 * @property string $DUE_DATE
 * @property string $APPLIED_RATE
 * @property string $INVOICE
 * @property string $NOTE
 * @property string $CREATE_TIME
 * @property string $CREATED_BY_ID
 * @property string $CREATED_BY_NAME
 * @property string $LAST_UPDATE
 * @property string $UPDATED_BY_ID
 * @property string $UPDATED_BY_NAME
 * @property string $aliasModel
 */
abstract class ShipReservationDtr extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.SHIP_RESERVATION_DTR';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['DTR_ID'], 'required'],
            [['CNT_40HC', 'CNT_40', 'CNT_20', 'LCL', 'FLAG_PRIORITY'], 'integer'],
            [['ETD', 'ETD_SUB', 'DUE_DATE', 'CREATE_TIME', 'LAST_UPDATE'], 'safe'],
            [['DTR_ID', 'HDR_ID', 'RESERVATION_NO', 'DO_NO', 'BL_NO', 'STATUS', 'SHIPPER', 'POL', 'POD', 'CARRIER', 'FLAG_DESC', 'KD_FLAG', 'PERIOD', 'INVOICE'], 'string', 'max' => 50],
            [['YCJ_REF_NO', 'CREATED_BY_ID', 'UPDATED_BY_ID'], 'string', 'max' => 20],
            [['HELP'], 'string', 'max' => 1],
            [['APPLIED_RATE', 'NOTE'], 'string', 'max' => 100],
            [['CREATED_BY_NAME', 'UPDATED_BY_NAME'], 'string', 'max' => 250],
            [['DTR_ID'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'DTR_ID' => 'Dtr ID',
            'HDR_ID' => 'Hdr ID',
            'YCJ_REF_NO' => 'Ycj Ref No',
            'RESERVATION_NO' => 'Reservation No',
            'DO_NO' => 'Do No',
            'BL_NO' => 'Bl No',
            'HELP' => 'Help',
            'STATUS' => 'Status',
            'SHIPPER' => 'Shipper',
            'POL' => 'Pol',
            'POD' => 'Pod',
            'CNT_40HC' => 'Cnt 40 Hc',
            'CNT_40' => 'Cnt 40',
            'CNT_20' => 'Cnt 20',
            'LCL' => 'Lcl',
            'CARRIER' => 'Carrier',
            'FLAG_PRIORITY' => 'Flag Priority',
            'FLAG_DESC' => 'Flag Desc',
            'ETD' => 'Etd',
            'ETD_SUB' => 'Etd Sub',
            'KD_FLAG' => 'Kd Flag',
            'PERIOD' => 'Period',
            'DUE_DATE' => 'Due Date',
            'APPLIED_RATE' => 'Applied Rate',
            'INVOICE' => 'Invoice',
            'NOTE' => 'Note',
            'CREATE_TIME' => 'Create Time',
            'CREATED_BY_ID' => 'Created By ID',
            'CREATED_BY_NAME' => 'Created By Name',
            'LAST_UPDATE' => 'Last Update',
            'UPDATED_BY_ID' => 'Updated By ID',
            'UPDATED_BY_NAME' => 'Updated By Name',
        ];
    }




}
