<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.SKILL_MASTER".
 *
 * @property string $skill_id
 * @property string $skill_desc
 * @property string $skill_group
 * @property string $skill_group_desc
 * @property double $WW01
 * @property double $WW02
 * @property double $WW03
 * @property double $WW04
 * @property double $WI01
 * @property double $WI02
 * @property double $WI03
 * @property double $WP01
 * @property double $WM01
 * @property double $WM02
 * @property double $WM03
 * @property double $WU01
 * @property double $WS01
 * @property double $WF01
 * @property string $aliasModel
 */
abstract class SkillMaster extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.SKILL_MASTER';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['skill_id'], 'required'],
            [['skill_id', 'skill_desc', 'skill_group', 'skill_group_desc'], 'string'],
            [['WW01', 'WW02', 'WW03', 'WW04', 'WI01', 'WI02', 'WI03', 'WP01', 'WM01', 'WM02', 'WM03', 'WU01', 'WS01', 'WF01'], 'number'],
            [['skill_id'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'skill_id' => 'Skill ID',
            'skill_desc' => 'Skill Desc',
            'skill_group' => 'Skill Group',
            'skill_group_desc' => 'Skill Group Desc',
            'WW01' => 'Ww01',
            'WW02' => 'Ww02',
            'WW03' => 'Ww03',
            'WW04' => 'Ww04',
            'WI01' => 'Wi01',
            'WI02' => 'Wi02',
            'WI03' => 'Wi03',
            'WP01' => 'Wp01',
            'WM01' => 'Wm01',
            'WM02' => 'Wm02',
            'WM03' => 'Wm03',
            'WU01' => 'Wu01',
            'WS01' => 'Ws01',
            'WF01' => 'Wf01',
        ];
    }




}
