<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.SKILL_MASTER_DAILY_TRAINING".
 *
 * @property string $POST_DATE
 * @property string $NIK
 * @property string $NAMA_KARYAWAN
 * @property string $loc_id
 * @property string $aliasModel
 */
abstract class SkillMasterDailyTraining extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.SKILL_MASTER_DAILY_TRAINING';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['POST_DATE'], 'safe'],
            [['NIK', 'NAMA_KARYAWAN', 'loc_id'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'POST_DATE' => 'Post  Date',
            'NIK' => 'Nik',
            'NAMA_KARYAWAN' => 'Nama  Karyawan',
            'loc_id' => 'Loc ID',
        ];
    }




}
