<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.SMT_PCB_LOG_LINE_BALANCE".
 *
 * @property string $start_period
 * @property string $machine
 * @property string $mounter_stage
 * @property string $stage
 * @property double $mount_ct_total_avg
 * @property string $line
 * @property string $aliasModel
 */
abstract class SmtLogLineBalance extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.SMT_PCB_LOG_LINE_BALANCE';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['mount_ct_total_avg'], 'number'],
            [['start_period'], 'string', 'max' => 6],
            [['machine', 'mounter_stage', 'stage', 'line'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'start_period' => 'Start Period',
            'machine' => 'Machine',
            'mounter_stage' => 'Mounter Stage',
            'stage' => 'Stage',
            'mount_ct_total_avg' => 'Mount Ct Total Avg',
            'line' => 'Line',
        ];
    }




}
