<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.SMT_OUTPUT_MONTHLY_INSERT_POINT_02".
 *
 * @property string $period
 * @property string $child_all
 * @property string $child_desc_all
 * @property double $total_qty
 * @property double $planed_loss_minute
 * @property double $out_section_minute
 * @property integer $POINT_SMT
 * @property double $POINT_FCA
 * @property double $TOTAL_POINT_SMT
 * @property double $TOTAL_POINT_FCA
 * @property string $aliasModel
 */
abstract class SmtOutputMonthlyInsertPoint02 extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.SMT_OUTPUT_MONTHLY_INSERT_POINT_02';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['total_qty', 'planed_loss_minute', 'out_section_minute', 'POINT_FCA', 'TOTAL_POINT_SMT', 'TOTAL_POINT_FCA'], 'number'],
            [['POINT_SMT'], 'integer'],
            [['period'], 'string', 'max' => 6],
            [['child_all'], 'string', 'max' => 15],
            [['child_desc_all'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'period' => 'Period',
            'child_all' => 'Child All',
            'child_desc_all' => 'Child Desc All',
            'total_qty' => 'Total Qty',
            'planed_loss_minute' => 'Planed Loss Minute',
            'out_section_minute' => 'Out Section Minute',
            'POINT_SMT' => 'Point Smt',
            'POINT_FCA' => 'Point Fca',
            'TOTAL_POINT_SMT' => 'Total Point Smt',
            'TOTAL_POINT_FCA' => 'Total Point Fca',
        ];
    }




}
