<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.SMT_PCB_LOG_WORKING_RATIO_BY_DAY_RESULT".
 *
 * @property string $shift_period
 * @property string $shift_date
 * @property string $machine
 * @property string $mounter_stage
 * @property integer $day_on_second
 * @property double $working_ratio_by_day
 * @property string $stage
 * @property string $line
 * @property string $aliasModel
 */
abstract class SmtWorkingRatioByDayResult extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.SMT_PCB_LOG_WORKING_RATIO_BY_DAY_RESULT';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['shift_date'], 'safe'],
            [['day_on_second'], 'required'],
            [['day_on_second'], 'integer'],
            [['working_ratio_by_day'], 'number'],
            [['shift_period'], 'string', 'max' => 6],
            [['machine', 'mounter_stage', 'stage', 'line'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'shift_period' => 'Shift Period',
            'shift_date' => 'Shift Date',
            'machine' => 'Machine',
            'mounter_stage' => 'Mounter Stage',
            'day_on_second' => 'Day On Second',
            'working_ratio_by_day' => 'Working Ratio By Day',
            'stage' => 'Stage',
            'line' => 'Line',
        ];
    }




}
