<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.SPL_HDR".
 *
 * @property string $SPL_HDR_ID
 * @property string $SPL_BARCODE
 * @property string $TGL_LEMBUR
 * @property string $JENIS_LEMBUR
 * @property string $CC_ID
 * @property string $CC_GROUP
 * @property string $CC_DESC
 * @property string $USER_ID
 * @property string $USER_DESC
 * @property string $USER_LAST_UPDATE
 * @property string $DOC_RCV_DATE
 * @property string $USER_DOC_RCV
 * @property string $USER_DESC_DOC_RCV
 * @property string $DOC_VALIDATION_DATE
 * @property string $URAIAN_UMUM
 * @property string $STAT
 * @property string $aliasModel
 */
abstract class SplHdr extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.SPL_HDR';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['SPL_HDR_ID', 'SPL_BARCODE', 'TGL_LEMBUR'], 'required'],
            [['SPL_HDR_ID', 'SPL_BARCODE', 'JENIS_LEMBUR', 'CC_ID', 'CC_GROUP', 'CC_DESC', 'USER_ID', 'USER_DESC', 'USER_DOC_RCV', 'USER_DESC_DOC_RCV', 'URAIAN_UMUM', 'STAT'], 'string'],
            [['TGL_LEMBUR', 'USER_LAST_UPDATE', 'DOC_RCV_DATE', 'DOC_VALIDATION_DATE'], 'safe'],
            [['SPL_HDR_ID'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'SPL_HDR_ID' => 'Spl  Hdr  ID',
            'SPL_BARCODE' => 'Spl  Barcode',
            'TGL_LEMBUR' => 'Tgl  Lembur',
            'JENIS_LEMBUR' => 'Jenis  Lembur',
            'CC_ID' => 'Cc  ID',
            'CC_GROUP' => 'Cc  Group',
            'CC_DESC' => 'Cc  Desc',
            'USER_ID' => 'User  ID',
            'USER_DESC' => 'User  Desc',
            'USER_LAST_UPDATE' => 'User  Last  Update',
            'DOC_RCV_DATE' => 'Doc  Rcv  Date',
            'USER_DOC_RCV' => 'User  Doc  Rcv',
            'USER_DESC_DOC_RCV' => 'User  Desc  Doc  Rcv',
            'DOC_VALIDATION_DATE' => 'Doc  Validation  Date',
            'URAIAN_UMUM' => 'Uraian  Umum',
            'STAT' => 'Stat',
        ];
    }




}
