<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.STORE_ITEM".
 *
 * @property string $ITEM
 * @property string $ITEM_DESC
 * @property string $UM
 * @property string $PUR_LOC
 * @property string $PUR_LOC_DESC
 * @property string $PIC
 * @property string $RACK
 * @property string $RACK_LOC
 * @property string $IQA
 * @property string $USER_ID
 * @property string $USER_DESC
 * @property string $LAST_UPDATE
 * @property string $STORAGE
 * @property string $PIC_DELIVERY
 * @property string $DIVISION
 * @property string $LEADER
 * @property double $multi_qty
 * @property double $dts_lt
 * @property string $del_type
 * @property double $SAFETY
 * @property string $MAT_CLASS
 * @property string $AREA
 * @property string $aliasModel
 */
abstract class StoreItemWsus extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.STORE_ITEM';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_wsus');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ITEM'], 'required'],
            [['ITEM', 'ITEM_DESC', 'UM', 'PUR_LOC', 'PUR_LOC_DESC', 'PIC', 'RACK', 'RACK_LOC', 'IQA', 'USER_ID', 'USER_DESC', 'STORAGE', 'PIC_DELIVERY', 'DIVISION', 'LEADER', 'del_type', 'MAT_CLASS', 'AREA'], 'string'],
            [['LAST_UPDATE'], 'safe'],
            [['multi_qty', 'dts_lt', 'SAFETY'], 'number'],
            [['ITEM'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ITEM' => 'Item',
            'ITEM_DESC' => 'Item  Desc',
            'UM' => 'Um',
            'PUR_LOC' => 'Pur  Loc',
            'PUR_LOC_DESC' => 'Pur  Loc  Desc',
            'PIC' => 'Pic',
            'RACK' => 'Rack',
            'RACK_LOC' => 'Rack  Loc',
            'IQA' => 'Iqa',
            'USER_ID' => 'User  ID',
            'USER_DESC' => 'User  Desc',
            'LAST_UPDATE' => 'Last  Update',
            'STORAGE' => 'Storage',
            'PIC_DELIVERY' => 'Pic  Delivery',
            'DIVISION' => 'Division',
            'LEADER' => 'Leader',
            'multi_qty' => 'Multi Qty',
            'dts_lt' => 'Dts Lt',
            'del_type' => 'Del Type',
            'SAFETY' => 'Safety',
            'MAT_CLASS' => 'Mat  Class',
            'AREA' => 'Area',
        ];
    }




}
