<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.SUNFISH_WORKING_TIME".
 *
 * @property string $ID
 * @property string $PERIOD
 * @property string $COST_CENTER_CODE
 * @property string $COST_CENTER_NAME
 * @property integer $SHIFT1_DIRECT_MP
 * @property integer $SHIFT2_DIRECT_MP
 * @property integer $SHIFT3_DIRECT_MP
 * @property integer $SHIFT1_DIRECT_WT
 * @property integer $SHIFT2_DIRECT_WT
 * @property integer $SHIFT3_DIRECT_WT
 * @property integer $SHIFT1_INDIRECT_MP
 * @property integer $SHIFT2_INDIRECT_MP
 * @property integer $SHIFT3_INDIRECT_MP
 * @property integer $SHIFT1_INDIRECT_WT
 * @property integer $SHIFT2_INDIRECT_WT
 * @property integer $SHIFT3_INDIRECT_WT
 * @property string $LAST_UPDATE
 * @property string $aliasModel
 */
abstract class SunfishWorkingTime extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.SUNFISH_WORKING_TIME';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ID'], 'required'],
            [['SHIFT1_DIRECT_MP', 'SHIFT2_DIRECT_MP', 'SHIFT3_DIRECT_MP', 'SHIFT1_DIRECT_WT', 'SHIFT2_DIRECT_WT', 'SHIFT3_DIRECT_WT', 'SHIFT1_INDIRECT_MP', 'SHIFT2_INDIRECT_MP', 'SHIFT3_INDIRECT_MP', 'SHIFT1_INDIRECT_WT', 'SHIFT2_INDIRECT_WT', 'SHIFT3_INDIRECT_WT'], 'integer'],
            [['LAST_UPDATE'], 'safe'],
            [['ID', 'COST_CENTER_NAME'], 'string', 'max' => 50],
            [['PERIOD', 'COST_CENTER_CODE'], 'string', 'max' => 10],
            [['ID'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ID' => 'ID',
            'PERIOD' => 'Period',
            'COST_CENTER_CODE' => 'Cost Center Code',
            'COST_CENTER_NAME' => 'Cost Center Name',
            'SHIFT1_DIRECT_MP' => 'Shift1 Direct Mp',
            'SHIFT2_DIRECT_MP' => 'Shift2 Direct Mp',
            'SHIFT3_DIRECT_MP' => 'Shift3 Direct Mp',
            'SHIFT1_DIRECT_WT' => 'Shift1 Direct Wt',
            'SHIFT2_DIRECT_WT' => 'Shift2 Direct Wt',
            'SHIFT3_DIRECT_WT' => 'Shift3 Direct Wt',
            'SHIFT1_INDIRECT_MP' => 'Shift1 Indirect Mp',
            'SHIFT2_INDIRECT_MP' => 'Shift2 Indirect Mp',
            'SHIFT3_INDIRECT_MP' => 'Shift3 Indirect Mp',
            'SHIFT1_INDIRECT_WT' => 'Shift1 Indirect Wt',
            'SHIFT2_INDIRECT_WT' => 'Shift2 Indirect Wt',
            'SHIFT3_INDIRECT_WT' => 'Shift3 Indirect Wt',
            'LAST_UPDATE' => 'Last Update',
        ];
    }




}
