<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "supplement_detail_view".
 *
 * @property string $date_spt
 * @property string $slip_spt
 * @property integer $stts_req
 * @property string $nm_line
 * @property string $part_numb
 * @property string $description
 * @property integer $total_req
 * @property string $reason
 * @property string $remarks_pc
 * @property string $remarks_wh
 * @property string $aliasModel
 */
abstract class SupplementDetailView extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'supplement_detail_view';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_supplement');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date_spt'], 'safe'],
            [['slip_spt', 'stts_req', 'nm_line', 'part_numb', 'total_req', 'reason'], 'required'],
            [['stts_req', 'total_req'], 'integer'],
            [['slip_spt', 'part_numb'], 'string', 'max' => 30],
            [['nm_line', 'reason'], 'string', 'max' => 20],
            [['description'], 'string', 'max' => 100],
            [['remarks_pc', 'remarks_wh'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'date_spt' => 'Date Spt',
            'slip_spt' => 'Slip Spt',
            'stts_req' => 'Stts Req',
            'nm_line' => 'Nm Line',
            'part_numb' => 'Part Numb',
            'description' => 'Description',
            'total_req' => 'Total Req',
            'reason' => 'Reason',
            'remarks_pc' => 'Remarks Pc',
            'remarks_wh' => 'Remarks Wh',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'stts_req' => '6 = OUTSTANDING',
        ]);
    }




}
