<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.TRACE_ITEM_DTR_LOC".
 *
 * @property integer $ID
 * @property string $LOC_DESC
 * @property integer $TOP_POS
 * @property integer $LEFT_POS
 * @property integer $FLAG
 * @property string $aliasModel
 */
abstract class TraceItemDtrLoc extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.TRACE_ITEM_DTR_LOC';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_wsus');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['TOP_POS', 'LEFT_POS', 'FLAG'], 'integer'],
            [['LOC_DESC'], 'string', 'max' => 150]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ID' => 'ID',
            'LOC_DESC' => 'Loc Desc',
            'TOP_POS' => 'Top Pos',
            'LEFT_POS' => 'Left Pos',
            'FLAG' => 'Flag',
        ];
    }




}
