<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "tb_visitor".
 *
 * @property string $pk
 * @property string $tgl
 * @property integer $emp_nik
 * @property string $emp_name
 * @property string $emp_dept
 * @property string $visitor_id
 * @property string $visitor_name
 * @property string $visitor_comp
 * @property integer $visitor_tot
 * @property string $visitor_reason
 * @property integer $meet
 * @property integer $status
 * @property string $status_date
 * @property string $card
 * @property integer $status_card
 * @property string $aliasModel
 */
abstract class Visitor extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tb_visitor';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_mis7');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['pk'], 'required'],
            [['tgl', 'status_date'], 'safe'],
            [['emp_nik', 'visitor_tot', 'meet', 'status', 'status_card'], 'integer'],
            [['pk', 'emp_name', 'emp_dept', 'visitor_id', 'visitor_name', 'visitor_comp', 'visitor_reason', 'card'], 'string', 'max' => 255],
            [['pk'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'pk' => 'Pk',
            'tgl' => 'Tgl',
            'emp_nik' => 'Emp Nik',
            'emp_name' => 'Emp Name',
            'emp_dept' => 'Emp Dept',
            'visitor_id' => 'Visitor ID',
            'visitor_name' => 'Visitor Name',
            'visitor_comp' => 'Visitor Comp',
            'visitor_tot' => 'Visitor Tot',
            'visitor_reason' => 'Visitor Reason',
            'meet' => 'Meet',
            'status' => 'Status',
            'status_date' => 'Status Date',
            'card' => 'Card',
            'status_card' => 'Status Card',
        ];
    }




}
