<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "weekly_shipping_out_view_01".
 *
 * @property integer $week_no
 * @property string $etd
 * @property string $ship
 * @property string $uniq
 * @property integer $so
 * @property integer $plan_qty
 * @property string $actual_qty
 * @property string $aliasModel
 */
abstract class WeeklyShippingOutView01 extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'weekly_shipping_out_view_01';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_mis7');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['week_no', 'so', 'plan_qty', 'actual_qty'], 'integer'],
            [['etd', 'ship', 'uniq'], 'required'],
            [['etd', 'ship'], 'safe'],
            [['uniq'], 'string', 'max' => 25]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'week_no' => 'Week No',
            'etd' => 'Etd',
            'ship' => 'Ship',
            'uniq' => 'Uniq',
            'so' => 'So',
            'plan_qty' => 'Plan Qty',
            'actual_qty' => 'Actual Qty',
        ];
    }




}
