<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.WIP_EFF_NEW_07".
 *
 * @property string $child_analyst
 * @property string $child_analyst_desc
 * @property string $period
 * @property string $post_date
 * @property string $LINE
 * @property integer $shift_count
 * @property double $lt_std
 * @property double $lt_gross
 * @property double $planed_loss_minute
 * @property double $out_section_minute
 * @property double $dandori_minute
 * @property double $break_down_minute
 * @property double $operating_loss_minute
 * @property double $operating_ratio
 * @property double $working_ratio
 * @property string $aliasModel
 */
abstract class WipEffNew07 extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.WIP_EFF_NEW_07';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['child_analyst', 'child_analyst_desc', 'period', 'LINE'], 'string'],
            [['post_date'], 'safe'],
            [['shift_count'], 'integer'],
            [['lt_std', 'lt_gross', 'planed_loss_minute', 'out_section_minute', 'dandori_minute', 'break_down_minute', 'operating_loss_minute', 'operating_ratio', 'working_ratio'], 'number']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'child_analyst' => 'Child Analyst',
            'child_analyst_desc' => 'Child Analyst Desc',
            'period' => 'Period',
            'post_date' => 'Post Date',
            'LINE' => 'Line',
            'shift_count' => 'Shift Count',
            'lt_std' => 'Lt Std',
            'lt_gross' => 'Lt Gross',
            'planed_loss_minute' => 'Planed Loss Minute',
            'out_section_minute' => 'Out Section Minute',
            'dandori_minute' => 'Dandori Minute',
            'break_down_minute' => 'Break Down Minute',
            'operating_loss_minute' => 'Operating Loss Minute',
            'operating_ratio' => 'Operating Ratio',
            'working_ratio' => 'Working Ratio',
        ];
    }




}
