<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.WIP_EFF_03_DANDORI_05".
 *
 * @property string $period
 * @property string $post_date
 * @property string $child_analyst
 * @property string $child_analyst_desc
 * @property string $LINE
 * @property double $dandori_second
 * @property double $lost_etc
 * @property integer $ITEM
 * @property integer $SHIFT_COUNT
 * @property integer $SHIFT_TIME
 * @property double $dandori_pct
 * @property string $aliasModel
 */
abstract class WipEff03Dandori05 extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.WIP_EFF_03_DANDORI_05';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['period', 'child_analyst', 'child_analyst_desc', 'LINE'], 'string'],
            [['post_date'], 'safe'],
            [['dandori_second', 'lost_etc', 'dandori_pct'], 'number'],
            [['ITEM', 'SHIFT_COUNT', 'SHIFT_TIME'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'period' => 'Period',
            'post_date' => 'Post Date',
            'child_analyst' => 'Child Analyst',
            'child_analyst_desc' => 'Child Analyst Desc',
            'LINE' => 'Line',
            'dandori_second' => 'Dandori Second',
            'lost_etc' => 'Lost Etc',
            'ITEM' => 'Item',
            'SHIFT_COUNT' => 'Shift  Count',
            'SHIFT_TIME' => 'Shift  Time',
            'dandori_pct' => 'Dandori Pct',
        ];
    }




}
