<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.WIP_FLOW_VIEW_02".
 *
 * @property string $period
 * @property string $child_analyst
 * @property string $child_analyst_desc
 * @property string $model_group
 * @property string $parent
 * @property string $parent_desc
 * @property string $period_line
 * @property string $due_date
 * @property double $plan_qty
 * @property double $act_qty
 * @property string $aliasModel
 */
abstract class WipFlowView02 extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.WIP_FLOW_VIEW_02';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['period', 'child_analyst', 'child_analyst_desc', 'model_group', 'parent', 'parent_desc', 'period_line'], 'string'],
            [['due_date'], 'safe'],
            [['plan_qty', 'act_qty'], 'number']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'period' => 'Period',
            'child_analyst' => 'Child Analyst',
            'child_analyst_desc' => 'Child Analyst Desc',
            'model_group' => 'Model Group',
            'parent' => 'Parent',
            'parent_desc' => 'Parent Desc',
            'period_line' => 'Period Line',
            'due_date' => 'Due Date',
            'plan_qty' => 'Plan Qty',
            'act_qty' => 'Act Qty',
        ];
    }




}
