<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.WIP_MODEL_GROUP".
 *
 * @property string $gmc
 * @property string $model_name
 * @property string $destination
 * @property string $line_fa
 * @property string $category_id
 * @property string $category_desc
 * @property string $aliasModel
 */
abstract class WipModelGroup extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.WIP_MODEL_GROUP';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['gmc'], 'required'],
            [['gmc', 'model_name', 'line_fa', 'category_desc'], 'string', 'max' => 20],
            [['destination', 'category_id'], 'string', 'max' => 5],
            [['gmc'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'gmc' => 'Gmc',
            'model_name' => 'Model Name',
            'destination' => 'Destination',
            'line_fa' => 'Line Fa',
            'category_id' => 'Category ID',
            'category_desc' => 'Category Desc',
        ];
    }




}
