<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "db_owner.WIP_MP_PLAN".
 *
 * @property string $plan_id
 * @property string $period
 * @property string $child_analyst
 * @property string $child_analyst_desc
 * @property integer $mp_plan
 * @property string $created_by_id
 * @property string $created_by_name
 * @property string $updated_by_id
 * @property string $updated_by_name
 * @property string $last_updated
 * @property string $aliasModel
 */
abstract class WipMpPlan extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'db_owner.WIP_MP_PLAN';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_sql_server');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['plan_id'], 'required'],
            [['mp_plan'], 'integer'],
            [['last_updated'], 'safe'],
            [['plan_id', 'child_analyst_desc'], 'string', 'max' => 50],
            [['period'], 'string', 'max' => 6],
            [['child_analyst'], 'string', 'max' => 10],
            [['created_by_id', 'updated_by_id'], 'string', 'max' => 20],
            [['created_by_name', 'updated_by_name'], 'string', 'max' => 250],
            [['plan_id'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'plan_id' => 'Plan ID',
            'period' => 'Period',
            'child_analyst' => 'Child Analyst',
            'child_analyst_desc' => 'Child Analyst Desc',
            'mp_plan' => 'Mp Plan',
            'created_by_id' => 'Created By ID',
            'created_by_name' => 'Created By Name',
            'updated_by_id' => 'Updated By ID',
            'updated_by_name' => 'Updated By Name',
            'last_updated' => 'Last Updated',
        ];
    }




}
